/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiWriteEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiWriteEnvelope{}

// ApiWriteEnvelope struct for ApiWriteEnvelope
type ApiWriteEnvelope struct {
	Data map[string]interface{} `json:"data"`
	RequestId string `json:"requestId"`
	AdditionalProperties map[string]interface{}
}

type _ApiWriteEnvelope ApiWriteEnvelope

// NewApiWriteEnvelope instantiates a new ApiWriteEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWriteEnvelope(data map[string]interface{}, requestId string) *ApiWriteEnvelope {
	this := ApiWriteEnvelope{}
	this.Data = data
	this.RequestId = requestId
	return &this
}

// NewApiWriteEnvelopeWithDefaults instantiates a new ApiWriteEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWriteEnvelopeWithDefaults() *ApiWriteEnvelope {
	this := ApiWriteEnvelope{}
	return &this
}

// GetData returns the Data field value
func (o *ApiWriteEnvelope) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApiWriteEnvelope) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApiWriteEnvelope) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetRequestId returns the RequestId field value
func (o *ApiWriteEnvelope) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ApiWriteEnvelope) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ApiWriteEnvelope) SetRequestId(v string) {
	o.RequestId = v
}

func (o ApiWriteEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiWriteEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["requestId"] = o.RequestId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiWriteEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"requestId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiWriteEnvelope := _ApiWriteEnvelope{}

	err = json.Unmarshal(data, &varApiWriteEnvelope)

	if err != nil {
		return err
	}

	*o = ApiWriteEnvelope(varApiWriteEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "requestId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiWriteEnvelope struct {
	value *ApiWriteEnvelope
	isSet bool
}

func (v NullableApiWriteEnvelope) Get() *ApiWriteEnvelope {
	return v.value
}

func (v *NullableApiWriteEnvelope) Set(val *ApiWriteEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWriteEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWriteEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWriteEnvelope(val *ApiWriteEnvelope) *NullableApiWriteEnvelope {
	return &NullableApiWriteEnvelope{value: val, isSet: true}
}

func (v NullableApiWriteEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWriteEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
