/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"fmt"
)

// checks if the MerchantTaxProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantTaxProfileRequest{}

// MerchantTaxProfileRequest struct for MerchantTaxProfileRequest
type MerchantTaxProfileRequest struct {
	Environment string `json:"environment"`
	DisplayName *string `json:"displayName,omitempty"`
	OriginAddress TaxAddress `json:"originAddress"`
	Registrations []MerchantTaxProfileRequestRegistrationsInner `json:"registrations"`
	AdditionalProperties map[string]interface{}
}

type _MerchantTaxProfileRequest MerchantTaxProfileRequest

// NewMerchantTaxProfileRequest instantiates a new MerchantTaxProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantTaxProfileRequest(environment string, originAddress TaxAddress, registrations []MerchantTaxProfileRequestRegistrationsInner) *MerchantTaxProfileRequest {
	this := MerchantTaxProfileRequest{}
	this.Environment = environment
	this.OriginAddress = originAddress
	this.Registrations = registrations
	return &this
}

// NewMerchantTaxProfileRequestWithDefaults instantiates a new MerchantTaxProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantTaxProfileRequestWithDefaults() *MerchantTaxProfileRequest {
	this := MerchantTaxProfileRequest{}
	return &this
}

// GetEnvironment returns the Environment field value
func (o *MerchantTaxProfileRequest) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *MerchantTaxProfileRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *MerchantTaxProfileRequest) SetEnvironment(v string) {
	o.Environment = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *MerchantTaxProfileRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantTaxProfileRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *MerchantTaxProfileRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *MerchantTaxProfileRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetOriginAddress returns the OriginAddress field value
func (o *MerchantTaxProfileRequest) GetOriginAddress() TaxAddress {
	if o == nil {
		var ret TaxAddress
		return ret
	}

	return o.OriginAddress
}

// GetOriginAddressOk returns a tuple with the OriginAddress field value
// and a boolean to check if the value has been set.
func (o *MerchantTaxProfileRequest) GetOriginAddressOk() (*TaxAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginAddress, true
}

// SetOriginAddress sets field value
func (o *MerchantTaxProfileRequest) SetOriginAddress(v TaxAddress) {
	o.OriginAddress = v
}

// GetRegistrations returns the Registrations field value
func (o *MerchantTaxProfileRequest) GetRegistrations() []MerchantTaxProfileRequestRegistrationsInner {
	if o == nil {
		var ret []MerchantTaxProfileRequestRegistrationsInner
		return ret
	}

	return o.Registrations
}

// GetRegistrationsOk returns a tuple with the Registrations field value
// and a boolean to check if the value has been set.
func (o *MerchantTaxProfileRequest) GetRegistrationsOk() ([]MerchantTaxProfileRequestRegistrationsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Registrations, true
}

// SetRegistrations sets field value
func (o *MerchantTaxProfileRequest) SetRegistrations(v []MerchantTaxProfileRequestRegistrationsInner) {
	o.Registrations = v
}

func (o MerchantTaxProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantTaxProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment"] = o.Environment
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	toSerialize["originAddress"] = o.OriginAddress
	toSerialize["registrations"] = o.Registrations

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MerchantTaxProfileRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environment",
		"originAddress",
		"registrations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantTaxProfileRequest := _MerchantTaxProfileRequest{}

	err = json.Unmarshal(data, &varMerchantTaxProfileRequest)

	if err != nil {
		return err
	}

	*o = MerchantTaxProfileRequest(varMerchantTaxProfileRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environment")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "originAddress")
		delete(additionalProperties, "registrations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMerchantTaxProfileRequest struct {
	value *MerchantTaxProfileRequest
	isSet bool
}

func (v NullableMerchantTaxProfileRequest) Get() *MerchantTaxProfileRequest {
	return v.value
}

func (v *NullableMerchantTaxProfileRequest) Set(val *MerchantTaxProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantTaxProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantTaxProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantTaxProfileRequest(val *MerchantTaxProfileRequest) *NullableMerchantTaxProfileRequest {
	return &NullableMerchantTaxProfileRequest{value: val, isSet: true}
}

func (v NullableMerchantTaxProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantTaxProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
