/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantProfileDate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantProfileDate{}

// MerchantProfileDate struct for MerchantProfileDate
type MerchantProfileDate struct {
	Day float32 `json:"day"`
	Month float32 `json:"month"`
	Year float32 `json:"year"`
}

type _MerchantProfileDate MerchantProfileDate

// NewMerchantProfileDate instantiates a new MerchantProfileDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantProfileDate(day float32, month float32, year float32) *MerchantProfileDate {
	this := MerchantProfileDate{}
	this.Day = day
	this.Month = month
	this.Year = year
	return &this
}

// NewMerchantProfileDateWithDefaults instantiates a new MerchantProfileDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantProfileDateWithDefaults() *MerchantProfileDate {
	this := MerchantProfileDate{}
	return &this
}

// GetDay returns the Day field value
func (o *MerchantProfileDate) GetDay() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *MerchantProfileDate) GetDayOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *MerchantProfileDate) SetDay(v float32) {
	o.Day = v
}

// GetMonth returns the Month field value
func (o *MerchantProfileDate) GetMonth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Month
}

// GetMonthOk returns a tuple with the Month field value
// and a boolean to check if the value has been set.
func (o *MerchantProfileDate) GetMonthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Month, true
}

// SetMonth sets field value
func (o *MerchantProfileDate) SetMonth(v float32) {
	o.Month = v
}

// GetYear returns the Year field value
func (o *MerchantProfileDate) GetYear() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *MerchantProfileDate) GetYearOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *MerchantProfileDate) SetYear(v float32) {
	o.Year = v
}

func (o MerchantProfileDate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantProfileDate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["day"] = o.Day
	toSerialize["month"] = o.Month
	toSerialize["year"] = o.Year
	return toSerialize, nil
}

func (o *MerchantProfileDate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"day",
		"month",
		"year",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantProfileDate := _MerchantProfileDate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantProfileDate)

	if err != nil {
		return err
	}

	*o = MerchantProfileDate(varMerchantProfileDate)

	return err
}

type NullableMerchantProfileDate struct {
	value *MerchantProfileDate
	isSet bool
}

func (v NullableMerchantProfileDate) Get() *MerchantProfileDate {
	return v.value
}

func (v *NullableMerchantProfileDate) Set(val *MerchantProfileDate) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantProfileDate) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantProfileDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantProfileDate(val *MerchantProfileDate) *NullableMerchantProfileDate {
	return &NullableMerchantProfileDate{value: val, isSet: true}
}

func (v NullableMerchantProfileDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantProfileDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
