/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
)

// checks if the WebhookEndpointSecretRotateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointSecretRotateRequest{}

// WebhookEndpointSecretRotateRequest struct for WebhookEndpointSecretRotateRequest
type WebhookEndpointSecretRotateRequest struct {
	GracePeriodSeconds *int32 `json:"gracePeriodSeconds,omitempty"`
}

// NewWebhookEndpointSecretRotateRequest instantiates a new WebhookEndpointSecretRotateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointSecretRotateRequest() *WebhookEndpointSecretRotateRequest {
	this := WebhookEndpointSecretRotateRequest{}
	return &this
}

// NewWebhookEndpointSecretRotateRequestWithDefaults instantiates a new WebhookEndpointSecretRotateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointSecretRotateRequestWithDefaults() *WebhookEndpointSecretRotateRequest {
	this := WebhookEndpointSecretRotateRequest{}
	return &this
}

// GetGracePeriodSeconds returns the GracePeriodSeconds field value if set, zero value otherwise.
func (o *WebhookEndpointSecretRotateRequest) GetGracePeriodSeconds() int32 {
	if o == nil || IsNil(o.GracePeriodSeconds) {
		var ret int32
		return ret
	}
	return *o.GracePeriodSeconds
}

// GetGracePeriodSecondsOk returns a tuple with the GracePeriodSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSecretRotateRequest) GetGracePeriodSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.GracePeriodSeconds) {
		return nil, false
	}
	return o.GracePeriodSeconds, true
}

// HasGracePeriodSeconds returns a boolean if a field has been set.
func (o *WebhookEndpointSecretRotateRequest) HasGracePeriodSeconds() bool {
	if o != nil && !IsNil(o.GracePeriodSeconds) {
		return true
	}

	return false
}

// SetGracePeriodSeconds gets a reference to the given int32 and assigns it to the GracePeriodSeconds field.
func (o *WebhookEndpointSecretRotateRequest) SetGracePeriodSeconds(v int32) {
	o.GracePeriodSeconds = &v
}

func (o WebhookEndpointSecretRotateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointSecretRotateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GracePeriodSeconds) {
		toSerialize["gracePeriodSeconds"] = o.GracePeriodSeconds
	}
	return toSerialize, nil
}

type NullableWebhookEndpointSecretRotateRequest struct {
	value *WebhookEndpointSecretRotateRequest
	isSet bool
}

func (v NullableWebhookEndpointSecretRotateRequest) Get() *WebhookEndpointSecretRotateRequest {
	return v.value
}

func (v *NullableWebhookEndpointSecretRotateRequest) Set(val *WebhookEndpointSecretRotateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointSecretRotateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointSecretRotateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointSecretRotateRequest(val *WebhookEndpointSecretRotateRequest) *NullableWebhookEndpointSecretRotateRequest {
	return &NullableWebhookEndpointSecretRotateRequest{value: val, isSet: true}
}

func (v NullableWebhookEndpointSecretRotateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointSecretRotateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
