/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"time"
)

// checks if the BillingOrderFormsExpireDueRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingOrderFormsExpireDueRequest{}

// BillingOrderFormsExpireDueRequest struct for BillingOrderFormsExpireDueRequest
type BillingOrderFormsExpireDueRequest struct {
	Now *time.Time `json:"now,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

// NewBillingOrderFormsExpireDueRequest instantiates a new BillingOrderFormsExpireDueRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingOrderFormsExpireDueRequest() *BillingOrderFormsExpireDueRequest {
	this := BillingOrderFormsExpireDueRequest{}
	return &this
}

// NewBillingOrderFormsExpireDueRequestWithDefaults instantiates a new BillingOrderFormsExpireDueRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingOrderFormsExpireDueRequestWithDefaults() *BillingOrderFormsExpireDueRequest {
	this := BillingOrderFormsExpireDueRequest{}
	return &this
}

// GetNow returns the Now field value if set, zero value otherwise.
func (o *BillingOrderFormsExpireDueRequest) GetNow() time.Time {
	if o == nil || IsNil(o.Now) {
		var ret time.Time
		return ret
	}
	return *o.Now
}

// GetNowOk returns a tuple with the Now field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingOrderFormsExpireDueRequest) GetNowOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Now) {
		return nil, false
	}
	return o.Now, true
}

// HasNow returns a boolean if a field has been set.
func (o *BillingOrderFormsExpireDueRequest) HasNow() bool {
	if o != nil && !IsNil(o.Now) {
		return true
	}

	return false
}

// SetNow gets a reference to the given time.Time and assigns it to the Now field.
func (o *BillingOrderFormsExpireDueRequest) SetNow(v time.Time) {
	o.Now = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *BillingOrderFormsExpireDueRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingOrderFormsExpireDueRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *BillingOrderFormsExpireDueRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *BillingOrderFormsExpireDueRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o BillingOrderFormsExpireDueRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingOrderFormsExpireDueRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Now) {
		toSerialize["now"] = o.Now
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullableBillingOrderFormsExpireDueRequest struct {
	value *BillingOrderFormsExpireDueRequest
	isSet bool
}

func (v NullableBillingOrderFormsExpireDueRequest) Get() *BillingOrderFormsExpireDueRequest {
	return v.value
}

func (v *NullableBillingOrderFormsExpireDueRequest) Set(val *BillingOrderFormsExpireDueRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingOrderFormsExpireDueRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingOrderFormsExpireDueRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingOrderFormsExpireDueRequest(val *BillingOrderFormsExpireDueRequest) *NullableBillingOrderFormsExpireDueRequest {
	return &NullableBillingOrderFormsExpireDueRequest{value: val, isSet: true}
}

func (v NullableBillingOrderFormsExpireDueRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingOrderFormsExpireDueRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
