/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingQuoteLineInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingQuoteLineInput{}

// BillingQuoteLineInput struct for BillingQuoteLineInput
type BillingQuoteLineInput struct {
	PriceId string `json:"priceId"`
	Quantity *int32 `json:"quantity,omitempty"`
	// Negotiated minor-unit amount. Overrides the catalog price when set.
	UnitAmount *int32 `json:"unitAmount,omitempty"`
	Description *string `json:"description,omitempty"`
}

type _BillingQuoteLineInput BillingQuoteLineInput

// NewBillingQuoteLineInput instantiates a new BillingQuoteLineInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingQuoteLineInput(priceId string) *BillingQuoteLineInput {
	this := BillingQuoteLineInput{}
	this.PriceId = priceId
	return &this
}

// NewBillingQuoteLineInputWithDefaults instantiates a new BillingQuoteLineInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingQuoteLineInputWithDefaults() *BillingQuoteLineInput {
	this := BillingQuoteLineInput{}
	return &this
}

// GetPriceId returns the PriceId field value
func (o *BillingQuoteLineInput) GetPriceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceId
}

// GetPriceIdOk returns a tuple with the PriceId field value
// and a boolean to check if the value has been set.
func (o *BillingQuoteLineInput) GetPriceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceId, true
}

// SetPriceId sets field value
func (o *BillingQuoteLineInput) SetPriceId(v string) {
	o.PriceId = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *BillingQuoteLineInput) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingQuoteLineInput) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *BillingQuoteLineInput) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *BillingQuoteLineInput) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetUnitAmount returns the UnitAmount field value if set, zero value otherwise.
func (o *BillingQuoteLineInput) GetUnitAmount() int32 {
	if o == nil || IsNil(o.UnitAmount) {
		var ret int32
		return ret
	}
	return *o.UnitAmount
}

// GetUnitAmountOk returns a tuple with the UnitAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingQuoteLineInput) GetUnitAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitAmount) {
		return nil, false
	}
	return o.UnitAmount, true
}

// HasUnitAmount returns a boolean if a field has been set.
func (o *BillingQuoteLineInput) HasUnitAmount() bool {
	if o != nil && !IsNil(o.UnitAmount) {
		return true
	}

	return false
}

// SetUnitAmount gets a reference to the given int32 and assigns it to the UnitAmount field.
func (o *BillingQuoteLineInput) SetUnitAmount(v int32) {
	o.UnitAmount = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BillingQuoteLineInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingQuoteLineInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BillingQuoteLineInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BillingQuoteLineInput) SetDescription(v string) {
	o.Description = &v
}

func (o BillingQuoteLineInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingQuoteLineInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["priceId"] = o.PriceId
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.UnitAmount) {
		toSerialize["unitAmount"] = o.UnitAmount
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *BillingQuoteLineInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"priceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingQuoteLineInput := _BillingQuoteLineInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingQuoteLineInput)

	if err != nil {
		return err
	}

	*o = BillingQuoteLineInput(varBillingQuoteLineInput)

	return err
}

type NullableBillingQuoteLineInput struct {
	value *BillingQuoteLineInput
	isSet bool
}

func (v NullableBillingQuoteLineInput) Get() *BillingQuoteLineInput {
	return v.value
}

func (v *NullableBillingQuoteLineInput) Set(val *BillingQuoteLineInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingQuoteLineInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingQuoteLineInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingQuoteLineInput(val *BillingQuoteLineInput) *NullableBillingQuoteLineInput {
	return &NullableBillingQuoteLineInput{value: val, isSet: true}
}

func (v NullableBillingQuoteLineInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingQuoteLineInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
