/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RevokeEntitlementRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeEntitlementRequest{}

// RevokeEntitlementRequest struct for RevokeEntitlementRequest
type RevokeEntitlementRequest struct {
	CustomerExternalId string `json:"customerExternalId"`
	BillingAccountId *string `json:"billingAccountId,omitempty"`
	EntitlementKey string `json:"entitlementKey"`
	Source *string `json:"source,omitempty"`
	SourceRef *string `json:"sourceRef,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

type _RevokeEntitlementRequest RevokeEntitlementRequest

// NewRevokeEntitlementRequest instantiates a new RevokeEntitlementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeEntitlementRequest(customerExternalId string, entitlementKey string) *RevokeEntitlementRequest {
	this := RevokeEntitlementRequest{}
	this.CustomerExternalId = customerExternalId
	this.EntitlementKey = entitlementKey
	return &this
}

// NewRevokeEntitlementRequestWithDefaults instantiates a new RevokeEntitlementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeEntitlementRequestWithDefaults() *RevokeEntitlementRequest {
	this := RevokeEntitlementRequest{}
	return &this
}

// GetCustomerExternalId returns the CustomerExternalId field value
func (o *RevokeEntitlementRequest) GetCustomerExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerExternalId
}

// GetCustomerExternalIdOk returns a tuple with the CustomerExternalId field value
// and a boolean to check if the value has been set.
func (o *RevokeEntitlementRequest) GetCustomerExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerExternalId, true
}

// SetCustomerExternalId sets field value
func (o *RevokeEntitlementRequest) SetCustomerExternalId(v string) {
	o.CustomerExternalId = v
}

// GetBillingAccountId returns the BillingAccountId field value if set, zero value otherwise.
func (o *RevokeEntitlementRequest) GetBillingAccountId() string {
	if o == nil || IsNil(o.BillingAccountId) {
		var ret string
		return ret
	}
	return *o.BillingAccountId
}

// GetBillingAccountIdOk returns a tuple with the BillingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeEntitlementRequest) GetBillingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillingAccountId) {
		return nil, false
	}
	return o.BillingAccountId, true
}

// HasBillingAccountId returns a boolean if a field has been set.
func (o *RevokeEntitlementRequest) HasBillingAccountId() bool {
	if o != nil && !IsNil(o.BillingAccountId) {
		return true
	}

	return false
}

// SetBillingAccountId gets a reference to the given string and assigns it to the BillingAccountId field.
func (o *RevokeEntitlementRequest) SetBillingAccountId(v string) {
	o.BillingAccountId = &v
}

// GetEntitlementKey returns the EntitlementKey field value
func (o *RevokeEntitlementRequest) GetEntitlementKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntitlementKey
}

// GetEntitlementKeyOk returns a tuple with the EntitlementKey field value
// and a boolean to check if the value has been set.
func (o *RevokeEntitlementRequest) GetEntitlementKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntitlementKey, true
}

// SetEntitlementKey sets field value
func (o *RevokeEntitlementRequest) SetEntitlementKey(v string) {
	o.EntitlementKey = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *RevokeEntitlementRequest) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeEntitlementRequest) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *RevokeEntitlementRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *RevokeEntitlementRequest) SetSource(v string) {
	o.Source = &v
}

// GetSourceRef returns the SourceRef field value if set, zero value otherwise.
func (o *RevokeEntitlementRequest) GetSourceRef() string {
	if o == nil || IsNil(o.SourceRef) {
		var ret string
		return ret
	}
	return *o.SourceRef
}

// GetSourceRefOk returns a tuple with the SourceRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeEntitlementRequest) GetSourceRefOk() (*string, bool) {
	if o == nil || IsNil(o.SourceRef) {
		return nil, false
	}
	return o.SourceRef, true
}

// HasSourceRef returns a boolean if a field has been set.
func (o *RevokeEntitlementRequest) HasSourceRef() bool {
	if o != nil && !IsNil(o.SourceRef) {
		return true
	}

	return false
}

// SetSourceRef gets a reference to the given string and assigns it to the SourceRef field.
func (o *RevokeEntitlementRequest) SetSourceRef(v string) {
	o.SourceRef = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *RevokeEntitlementRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeEntitlementRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *RevokeEntitlementRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *RevokeEntitlementRequest) SetReason(v string) {
	o.Reason = &v
}

func (o RevokeEntitlementRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeEntitlementRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customerExternalId"] = o.CustomerExternalId
	if !IsNil(o.BillingAccountId) {
		toSerialize["billingAccountId"] = o.BillingAccountId
	}
	toSerialize["entitlementKey"] = o.EntitlementKey
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.SourceRef) {
		toSerialize["sourceRef"] = o.SourceRef
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *RevokeEntitlementRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerExternalId",
		"entitlementKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevokeEntitlementRequest := _RevokeEntitlementRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevokeEntitlementRequest)

	if err != nil {
		return err
	}

	*o = RevokeEntitlementRequest(varRevokeEntitlementRequest)

	return err
}

type NullableRevokeEntitlementRequest struct {
	value *RevokeEntitlementRequest
	isSet bool
}

func (v NullableRevokeEntitlementRequest) Get() *RevokeEntitlementRequest {
	return v.value
}

func (v *NullableRevokeEntitlementRequest) Set(val *RevokeEntitlementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeEntitlementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeEntitlementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeEntitlementRequest(val *RevokeEntitlementRequest) *NullableRevokeEntitlementRequest {
	return &NullableRevokeEntitlementRequest{value: val, isSet: true}
}

func (v NullableRevokeEntitlementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeEntitlementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
