/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaxLineEvidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxLineEvidence{}

// TaxLineEvidence struct for TaxLineEvidence
type TaxLineEvidence struct {
	SourceLineId string `json:"sourceLineId"`
	ClassificationKey string `json:"classificationKey"`
	ClassificationLabel string `json:"classificationLabel"`
	ClassificationVersion int32 `json:"classificationVersion"`
	ClassificationMappingVersion int32 `json:"classificationMappingVersion"`
	TaxableAmount int32 `json:"taxableAmount"`
	TaxAmount int32 `json:"taxAmount"`
	TaxBehavior TaxBehavior `json:"taxBehavior"`
	AmountIncludesTax bool `json:"amountIncludesTax"`
}

type _TaxLineEvidence TaxLineEvidence

// NewTaxLineEvidence instantiates a new TaxLineEvidence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxLineEvidence(sourceLineId string, classificationKey string, classificationLabel string, classificationVersion int32, classificationMappingVersion int32, taxableAmount int32, taxAmount int32, taxBehavior TaxBehavior, amountIncludesTax bool) *TaxLineEvidence {
	this := TaxLineEvidence{}
	this.SourceLineId = sourceLineId
	this.ClassificationKey = classificationKey
	this.ClassificationLabel = classificationLabel
	this.ClassificationVersion = classificationVersion
	this.ClassificationMappingVersion = classificationMappingVersion
	this.TaxableAmount = taxableAmount
	this.TaxAmount = taxAmount
	this.TaxBehavior = taxBehavior
	this.AmountIncludesTax = amountIncludesTax
	return &this
}

// NewTaxLineEvidenceWithDefaults instantiates a new TaxLineEvidence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxLineEvidenceWithDefaults() *TaxLineEvidence {
	this := TaxLineEvidence{}
	return &this
}

// GetSourceLineId returns the SourceLineId field value
func (o *TaxLineEvidence) GetSourceLineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceLineId
}

// GetSourceLineIdOk returns a tuple with the SourceLineId field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetSourceLineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceLineId, true
}

// SetSourceLineId sets field value
func (o *TaxLineEvidence) SetSourceLineId(v string) {
	o.SourceLineId = v
}

// GetClassificationKey returns the ClassificationKey field value
func (o *TaxLineEvidence) GetClassificationKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassificationKey
}

// GetClassificationKeyOk returns a tuple with the ClassificationKey field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetClassificationKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassificationKey, true
}

// SetClassificationKey sets field value
func (o *TaxLineEvidence) SetClassificationKey(v string) {
	o.ClassificationKey = v
}

// GetClassificationLabel returns the ClassificationLabel field value
func (o *TaxLineEvidence) GetClassificationLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassificationLabel
}

// GetClassificationLabelOk returns a tuple with the ClassificationLabel field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetClassificationLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassificationLabel, true
}

// SetClassificationLabel sets field value
func (o *TaxLineEvidence) SetClassificationLabel(v string) {
	o.ClassificationLabel = v
}

// GetClassificationVersion returns the ClassificationVersion field value
func (o *TaxLineEvidence) GetClassificationVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ClassificationVersion
}

// GetClassificationVersionOk returns a tuple with the ClassificationVersion field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetClassificationVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassificationVersion, true
}

// SetClassificationVersion sets field value
func (o *TaxLineEvidence) SetClassificationVersion(v int32) {
	o.ClassificationVersion = v
}

// GetClassificationMappingVersion returns the ClassificationMappingVersion field value
func (o *TaxLineEvidence) GetClassificationMappingVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ClassificationMappingVersion
}

// GetClassificationMappingVersionOk returns a tuple with the ClassificationMappingVersion field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetClassificationMappingVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassificationMappingVersion, true
}

// SetClassificationMappingVersion sets field value
func (o *TaxLineEvidence) SetClassificationMappingVersion(v int32) {
	o.ClassificationMappingVersion = v
}

// GetTaxableAmount returns the TaxableAmount field value
func (o *TaxLineEvidence) GetTaxableAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TaxableAmount
}

// GetTaxableAmountOk returns a tuple with the TaxableAmount field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetTaxableAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxableAmount, true
}

// SetTaxableAmount sets field value
func (o *TaxLineEvidence) SetTaxableAmount(v int32) {
	o.TaxableAmount = v
}

// GetTaxAmount returns the TaxAmount field value
func (o *TaxLineEvidence) GetTaxAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetTaxAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxAmount, true
}

// SetTaxAmount sets field value
func (o *TaxLineEvidence) SetTaxAmount(v int32) {
	o.TaxAmount = v
}

// GetTaxBehavior returns the TaxBehavior field value
func (o *TaxLineEvidence) GetTaxBehavior() TaxBehavior {
	if o == nil {
		var ret TaxBehavior
		return ret
	}

	return o.TaxBehavior
}

// GetTaxBehaviorOk returns a tuple with the TaxBehavior field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetTaxBehaviorOk() (*TaxBehavior, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxBehavior, true
}

// SetTaxBehavior sets field value
func (o *TaxLineEvidence) SetTaxBehavior(v TaxBehavior) {
	o.TaxBehavior = v
}

// GetAmountIncludesTax returns the AmountIncludesTax field value
func (o *TaxLineEvidence) GetAmountIncludesTax() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AmountIncludesTax
}

// GetAmountIncludesTaxOk returns a tuple with the AmountIncludesTax field value
// and a boolean to check if the value has been set.
func (o *TaxLineEvidence) GetAmountIncludesTaxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountIncludesTax, true
}

// SetAmountIncludesTax sets field value
func (o *TaxLineEvidence) SetAmountIncludesTax(v bool) {
	o.AmountIncludesTax = v
}

func (o TaxLineEvidence) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxLineEvidence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceLineId"] = o.SourceLineId
	toSerialize["classificationKey"] = o.ClassificationKey
	toSerialize["classificationLabel"] = o.ClassificationLabel
	toSerialize["classificationVersion"] = o.ClassificationVersion
	toSerialize["classificationMappingVersion"] = o.ClassificationMappingVersion
	toSerialize["taxableAmount"] = o.TaxableAmount
	toSerialize["taxAmount"] = o.TaxAmount
	toSerialize["taxBehavior"] = o.TaxBehavior
	toSerialize["amountIncludesTax"] = o.AmountIncludesTax
	return toSerialize, nil
}

func (o *TaxLineEvidence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceLineId",
		"classificationKey",
		"classificationLabel",
		"classificationVersion",
		"classificationMappingVersion",
		"taxableAmount",
		"taxAmount",
		"taxBehavior",
		"amountIncludesTax",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaxLineEvidence := _TaxLineEvidence{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaxLineEvidence)

	if err != nil {
		return err
	}

	*o = TaxLineEvidence(varTaxLineEvidence)

	return err
}

type NullableTaxLineEvidence struct {
	value *TaxLineEvidence
	isSet bool
}

func (v NullableTaxLineEvidence) Get() *TaxLineEvidence {
	return v.value
}

func (v *NullableTaxLineEvidence) Set(val *TaxLineEvidence) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxLineEvidence) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxLineEvidence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxLineEvidence(val *TaxLineEvidence) *NullableTaxLineEvidence {
	return &NullableTaxLineEvidence{value: val, isSet: true}
}

func (v NullableTaxLineEvidence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxLineEvidence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
