/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreditNoteCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditNoteCreateRequest{}

// CreditNoteCreateRequest struct for CreditNoteCreateRequest
type CreditNoteCreateRequest struct {
	CreditNoteId *string `json:"creditNoteId,omitempty"`
	InvoiceId string `json:"invoiceId"`
	Reason CreditNoteReason `json:"reason"`
	Description *string `json:"description,omitempty"`
	CreditAmount *int32 `json:"creditAmount,omitempty"`
	RefundAmount *int32 `json:"refundAmount,omitempty"`
	OffsetAmount *int32 `json:"offsetAmount,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Lines []CreditNoteCreateLine `json:"lines"`
}

type _CreditNoteCreateRequest CreditNoteCreateRequest

// NewCreditNoteCreateRequest instantiates a new CreditNoteCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditNoteCreateRequest(invoiceId string, reason CreditNoteReason, lines []CreditNoteCreateLine) *CreditNoteCreateRequest {
	this := CreditNoteCreateRequest{}
	this.InvoiceId = invoiceId
	this.Reason = reason
	this.Lines = lines
	return &this
}

// NewCreditNoteCreateRequestWithDefaults instantiates a new CreditNoteCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditNoteCreateRequestWithDefaults() *CreditNoteCreateRequest {
	this := CreditNoteCreateRequest{}
	return &this
}

// GetCreditNoteId returns the CreditNoteId field value if set, zero value otherwise.
func (o *CreditNoteCreateRequest) GetCreditNoteId() string {
	if o == nil || IsNil(o.CreditNoteId) {
		var ret string
		return ret
	}
	return *o.CreditNoteId
}

// GetCreditNoteIdOk returns a tuple with the CreditNoteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetCreditNoteIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreditNoteId) {
		return nil, false
	}
	return o.CreditNoteId, true
}

// HasCreditNoteId returns a boolean if a field has been set.
func (o *CreditNoteCreateRequest) HasCreditNoteId() bool {
	if o != nil && !IsNil(o.CreditNoteId) {
		return true
	}

	return false
}

// SetCreditNoteId gets a reference to the given string and assigns it to the CreditNoteId field.
func (o *CreditNoteCreateRequest) SetCreditNoteId(v string) {
	o.CreditNoteId = &v
}

// GetInvoiceId returns the InvoiceId field value
func (o *CreditNoteCreateRequest) GetInvoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceId, true
}

// SetInvoiceId sets field value
func (o *CreditNoteCreateRequest) SetInvoiceId(v string) {
	o.InvoiceId = v
}

// GetReason returns the Reason field value
func (o *CreditNoteCreateRequest) GetReason() CreditNoteReason {
	if o == nil {
		var ret CreditNoteReason
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetReasonOk() (*CreditNoteReason, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CreditNoteCreateRequest) SetReason(v CreditNoteReason) {
	o.Reason = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreditNoteCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreditNoteCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreditNoteCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCreditAmount returns the CreditAmount field value if set, zero value otherwise.
func (o *CreditNoteCreateRequest) GetCreditAmount() int32 {
	if o == nil || IsNil(o.CreditAmount) {
		var ret int32
		return ret
	}
	return *o.CreditAmount
}

// GetCreditAmountOk returns a tuple with the CreditAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetCreditAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditAmount) {
		return nil, false
	}
	return o.CreditAmount, true
}

// HasCreditAmount returns a boolean if a field has been set.
func (o *CreditNoteCreateRequest) HasCreditAmount() bool {
	if o != nil && !IsNil(o.CreditAmount) {
		return true
	}

	return false
}

// SetCreditAmount gets a reference to the given int32 and assigns it to the CreditAmount field.
func (o *CreditNoteCreateRequest) SetCreditAmount(v int32) {
	o.CreditAmount = &v
}

// GetRefundAmount returns the RefundAmount field value if set, zero value otherwise.
func (o *CreditNoteCreateRequest) GetRefundAmount() int32 {
	if o == nil || IsNil(o.RefundAmount) {
		var ret int32
		return ret
	}
	return *o.RefundAmount
}

// GetRefundAmountOk returns a tuple with the RefundAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetRefundAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.RefundAmount) {
		return nil, false
	}
	return o.RefundAmount, true
}

// HasRefundAmount returns a boolean if a field has been set.
func (o *CreditNoteCreateRequest) HasRefundAmount() bool {
	if o != nil && !IsNil(o.RefundAmount) {
		return true
	}

	return false
}

// SetRefundAmount gets a reference to the given int32 and assigns it to the RefundAmount field.
func (o *CreditNoteCreateRequest) SetRefundAmount(v int32) {
	o.RefundAmount = &v
}

// GetOffsetAmount returns the OffsetAmount field value if set, zero value otherwise.
func (o *CreditNoteCreateRequest) GetOffsetAmount() int32 {
	if o == nil || IsNil(o.OffsetAmount) {
		var ret int32
		return ret
	}
	return *o.OffsetAmount
}

// GetOffsetAmountOk returns a tuple with the OffsetAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetOffsetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.OffsetAmount) {
		return nil, false
	}
	return o.OffsetAmount, true
}

// HasOffsetAmount returns a boolean if a field has been set.
func (o *CreditNoteCreateRequest) HasOffsetAmount() bool {
	if o != nil && !IsNil(o.OffsetAmount) {
		return true
	}

	return false
}

// SetOffsetAmount gets a reference to the given int32 and assigns it to the OffsetAmount field.
func (o *CreditNoteCreateRequest) SetOffsetAmount(v int32) {
	o.OffsetAmount = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreditNoteCreateRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreditNoteCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CreditNoteCreateRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetLines returns the Lines field value
func (o *CreditNoteCreateRequest) GetLines() []CreditNoteCreateLine {
	if o == nil {
		var ret []CreditNoteCreateLine
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *CreditNoteCreateRequest) GetLinesOk() ([]CreditNoteCreateLine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *CreditNoteCreateRequest) SetLines(v []CreditNoteCreateLine) {
	o.Lines = v
}

func (o CreditNoteCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditNoteCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreditNoteId) {
		toSerialize["creditNoteId"] = o.CreditNoteId
	}
	toSerialize["invoiceId"] = o.InvoiceId
	toSerialize["reason"] = o.Reason
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CreditAmount) {
		toSerialize["creditAmount"] = o.CreditAmount
	}
	if !IsNil(o.RefundAmount) {
		toSerialize["refundAmount"] = o.RefundAmount
	}
	if !IsNil(o.OffsetAmount) {
		toSerialize["offsetAmount"] = o.OffsetAmount
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["lines"] = o.Lines
	return toSerialize, nil
}

func (o *CreditNoteCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invoiceId",
		"reason",
		"lines",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditNoteCreateRequest := _CreditNoteCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreditNoteCreateRequest)

	if err != nil {
		return err
	}

	*o = CreditNoteCreateRequest(varCreditNoteCreateRequest)

	return err
}

type NullableCreditNoteCreateRequest struct {
	value *CreditNoteCreateRequest
	isSet bool
}

func (v NullableCreditNoteCreateRequest) Get() *CreditNoteCreateRequest {
	return v.value
}

func (v *NullableCreditNoteCreateRequest) Set(val *CreditNoteCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditNoteCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditNoteCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditNoteCreateRequest(val *CreditNoteCreateRequest) *NullableCreditNoteCreateRequest {
	return &NullableCreditNoteCreateRequest{value: val, isSet: true}
}

func (v NullableCreditNoteCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditNoteCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
