/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CreateRecurringPayableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRecurringPayableRequest{}

// CreateRecurringPayableRequest struct for CreateRecurringPayableRequest
type CreateRecurringPayableRequest struct {
	SourceType string `json:"sourceType"`
	SourceId string `json:"sourceId"`
	DocumentId string `json:"documentId"`
	PaymentFieldId string `json:"paymentFieldId"`
	CustomerExternalId string `json:"customerExternalId"`
	BillingAccountId string `json:"billingAccountId"`
	MerchantAccountId *string `json:"merchantAccountId,omitempty"`
	// ISO 4217 alpha-3; only currencies processable on current rails are accepted
	Currency string `json:"currency"`
	LineItems []map[string]interface{} `json:"lineItems"`
	TaxMode string `json:"taxMode"`
	Taxable *bool `json:"taxable,omitempty"`
	TaxBehavior *string `json:"taxBehavior,omitempty"`
	TaxClassificationKey *string `json:"taxClassificationKey,omitempty"`
	CollectionIntent string `json:"collectionIntent"`
	// Adopter fee policy (modeled, not settlement-executed). Structure passed through to Vortex Payments.
	FeePolicy map[string]interface{} `json:"feePolicy"`
	Cadence CreateRecurringPayableRequestCadence `json:"cadence"`
	EndPolicy map[string]interface{} `json:"endPolicy"`
	StartAt time.Time `json:"startAt"`
	Metadata map[string]string `json:"metadata"`
	AdditionalProperties map[string]interface{}
}

type _CreateRecurringPayableRequest CreateRecurringPayableRequest

// NewCreateRecurringPayableRequest instantiates a new CreateRecurringPayableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRecurringPayableRequest(sourceType string, sourceId string, documentId string, paymentFieldId string, customerExternalId string, billingAccountId string, currency string, lineItems []map[string]interface{}, taxMode string, collectionIntent string, feePolicy map[string]interface{}, cadence CreateRecurringPayableRequestCadence, endPolicy map[string]interface{}, startAt time.Time, metadata map[string]string) *CreateRecurringPayableRequest {
	this := CreateRecurringPayableRequest{}
	this.SourceType = sourceType
	this.SourceId = sourceId
	this.DocumentId = documentId
	this.PaymentFieldId = paymentFieldId
	this.CustomerExternalId = customerExternalId
	this.BillingAccountId = billingAccountId
	this.Currency = currency
	this.LineItems = lineItems
	this.TaxMode = taxMode
	this.CollectionIntent = collectionIntent
	this.FeePolicy = feePolicy
	this.Cadence = cadence
	this.EndPolicy = endPolicy
	this.StartAt = startAt
	this.Metadata = metadata
	return &this
}

// NewCreateRecurringPayableRequestWithDefaults instantiates a new CreateRecurringPayableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRecurringPayableRequestWithDefaults() *CreateRecurringPayableRequest {
	this := CreateRecurringPayableRequest{}
	return &this
}

// GetSourceType returns the SourceType field value
func (o *CreateRecurringPayableRequest) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *CreateRecurringPayableRequest) SetSourceType(v string) {
	o.SourceType = v
}

// GetSourceId returns the SourceId field value
func (o *CreateRecurringPayableRequest) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *CreateRecurringPayableRequest) SetSourceId(v string) {
	o.SourceId = v
}

// GetDocumentId returns the DocumentId field value
func (o *CreateRecurringPayableRequest) GetDocumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentId, true
}

// SetDocumentId sets field value
func (o *CreateRecurringPayableRequest) SetDocumentId(v string) {
	o.DocumentId = v
}

// GetPaymentFieldId returns the PaymentFieldId field value
func (o *CreateRecurringPayableRequest) GetPaymentFieldId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentFieldId
}

// GetPaymentFieldIdOk returns a tuple with the PaymentFieldId field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetPaymentFieldIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentFieldId, true
}

// SetPaymentFieldId sets field value
func (o *CreateRecurringPayableRequest) SetPaymentFieldId(v string) {
	o.PaymentFieldId = v
}

// GetCustomerExternalId returns the CustomerExternalId field value
func (o *CreateRecurringPayableRequest) GetCustomerExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerExternalId
}

// GetCustomerExternalIdOk returns a tuple with the CustomerExternalId field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetCustomerExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerExternalId, true
}

// SetCustomerExternalId sets field value
func (o *CreateRecurringPayableRequest) SetCustomerExternalId(v string) {
	o.CustomerExternalId = v
}

// GetBillingAccountId returns the BillingAccountId field value
func (o *CreateRecurringPayableRequest) GetBillingAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingAccountId
}

// GetBillingAccountIdOk returns a tuple with the BillingAccountId field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetBillingAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingAccountId, true
}

// SetBillingAccountId sets field value
func (o *CreateRecurringPayableRequest) SetBillingAccountId(v string) {
	o.BillingAccountId = v
}

// GetMerchantAccountId returns the MerchantAccountId field value if set, zero value otherwise.
func (o *CreateRecurringPayableRequest) GetMerchantAccountId() string {
	if o == nil || IsNil(o.MerchantAccountId) {
		var ret string
		return ret
	}
	return *o.MerchantAccountId
}

// GetMerchantAccountIdOk returns a tuple with the MerchantAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetMerchantAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantAccountId) {
		return nil, false
	}
	return o.MerchantAccountId, true
}

// HasMerchantAccountId returns a boolean if a field has been set.
func (o *CreateRecurringPayableRequest) HasMerchantAccountId() bool {
	if o != nil && !IsNil(o.MerchantAccountId) {
		return true
	}

	return false
}

// SetMerchantAccountId gets a reference to the given string and assigns it to the MerchantAccountId field.
func (o *CreateRecurringPayableRequest) SetMerchantAccountId(v string) {
	o.MerchantAccountId = &v
}

// GetCurrency returns the Currency field value
func (o *CreateRecurringPayableRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CreateRecurringPayableRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetLineItems returns the LineItems field value
func (o *CreateRecurringPayableRequest) GetLineItems() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetLineItemsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.LineItems, true
}

// SetLineItems sets field value
func (o *CreateRecurringPayableRequest) SetLineItems(v []map[string]interface{}) {
	o.LineItems = v
}

// GetTaxMode returns the TaxMode field value
func (o *CreateRecurringPayableRequest) GetTaxMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaxMode
}

// GetTaxModeOk returns a tuple with the TaxMode field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetTaxModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxMode, true
}

// SetTaxMode sets field value
func (o *CreateRecurringPayableRequest) SetTaxMode(v string) {
	o.TaxMode = v
}

// GetTaxable returns the Taxable field value if set, zero value otherwise.
func (o *CreateRecurringPayableRequest) GetTaxable() bool {
	if o == nil || IsNil(o.Taxable) {
		var ret bool
		return ret
	}
	return *o.Taxable
}

// GetTaxableOk returns a tuple with the Taxable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetTaxableOk() (*bool, bool) {
	if o == nil || IsNil(o.Taxable) {
		return nil, false
	}
	return o.Taxable, true
}

// HasTaxable returns a boolean if a field has been set.
func (o *CreateRecurringPayableRequest) HasTaxable() bool {
	if o != nil && !IsNil(o.Taxable) {
		return true
	}

	return false
}

// SetTaxable gets a reference to the given bool and assigns it to the Taxable field.
func (o *CreateRecurringPayableRequest) SetTaxable(v bool) {
	o.Taxable = &v
}

// GetTaxBehavior returns the TaxBehavior field value if set, zero value otherwise.
func (o *CreateRecurringPayableRequest) GetTaxBehavior() string {
	if o == nil || IsNil(o.TaxBehavior) {
		var ret string
		return ret
	}
	return *o.TaxBehavior
}

// GetTaxBehaviorOk returns a tuple with the TaxBehavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetTaxBehaviorOk() (*string, bool) {
	if o == nil || IsNil(o.TaxBehavior) {
		return nil, false
	}
	return o.TaxBehavior, true
}

// HasTaxBehavior returns a boolean if a field has been set.
func (o *CreateRecurringPayableRequest) HasTaxBehavior() bool {
	if o != nil && !IsNil(o.TaxBehavior) {
		return true
	}

	return false
}

// SetTaxBehavior gets a reference to the given string and assigns it to the TaxBehavior field.
func (o *CreateRecurringPayableRequest) SetTaxBehavior(v string) {
	o.TaxBehavior = &v
}

// GetTaxClassificationKey returns the TaxClassificationKey field value if set, zero value otherwise.
func (o *CreateRecurringPayableRequest) GetTaxClassificationKey() string {
	if o == nil || IsNil(o.TaxClassificationKey) {
		var ret string
		return ret
	}
	return *o.TaxClassificationKey
}

// GetTaxClassificationKeyOk returns a tuple with the TaxClassificationKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetTaxClassificationKeyOk() (*string, bool) {
	if o == nil || IsNil(o.TaxClassificationKey) {
		return nil, false
	}
	return o.TaxClassificationKey, true
}

// HasTaxClassificationKey returns a boolean if a field has been set.
func (o *CreateRecurringPayableRequest) HasTaxClassificationKey() bool {
	if o != nil && !IsNil(o.TaxClassificationKey) {
		return true
	}

	return false
}

// SetTaxClassificationKey gets a reference to the given string and assigns it to the TaxClassificationKey field.
func (o *CreateRecurringPayableRequest) SetTaxClassificationKey(v string) {
	o.TaxClassificationKey = &v
}

// GetCollectionIntent returns the CollectionIntent field value
func (o *CreateRecurringPayableRequest) GetCollectionIntent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionIntent
}

// GetCollectionIntentOk returns a tuple with the CollectionIntent field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetCollectionIntentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionIntent, true
}

// SetCollectionIntent sets field value
func (o *CreateRecurringPayableRequest) SetCollectionIntent(v string) {
	o.CollectionIntent = v
}

// GetFeePolicy returns the FeePolicy field value
func (o *CreateRecurringPayableRequest) GetFeePolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.FeePolicy
}

// GetFeePolicyOk returns a tuple with the FeePolicy field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetFeePolicyOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.FeePolicy, true
}

// SetFeePolicy sets field value
func (o *CreateRecurringPayableRequest) SetFeePolicy(v map[string]interface{}) {
	o.FeePolicy = v
}

// GetCadence returns the Cadence field value
func (o *CreateRecurringPayableRequest) GetCadence() CreateRecurringPayableRequestCadence {
	if o == nil {
		var ret CreateRecurringPayableRequestCadence
		return ret
	}

	return o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetCadenceOk() (*CreateRecurringPayableRequestCadence, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cadence, true
}

// SetCadence sets field value
func (o *CreateRecurringPayableRequest) SetCadence(v CreateRecurringPayableRequestCadence) {
	o.Cadence = v
}

// GetEndPolicy returns the EndPolicy field value
func (o *CreateRecurringPayableRequest) GetEndPolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.EndPolicy
}

// GetEndPolicyOk returns a tuple with the EndPolicy field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetEndPolicyOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.EndPolicy, true
}

// SetEndPolicy sets field value
func (o *CreateRecurringPayableRequest) SetEndPolicy(v map[string]interface{}) {
	o.EndPolicy = v
}

// GetStartAt returns the StartAt field value
func (o *CreateRecurringPayableRequest) GetStartAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetStartAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *CreateRecurringPayableRequest) SetStartAt(v time.Time) {
	o.StartAt = v
}

// GetMetadata returns the Metadata field value
func (o *CreateRecurringPayableRequest) GetMetadata() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *CreateRecurringPayableRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *CreateRecurringPayableRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o CreateRecurringPayableRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRecurringPayableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceType"] = o.SourceType
	toSerialize["sourceId"] = o.SourceId
	toSerialize["documentId"] = o.DocumentId
	toSerialize["paymentFieldId"] = o.PaymentFieldId
	toSerialize["customerExternalId"] = o.CustomerExternalId
	toSerialize["billingAccountId"] = o.BillingAccountId
	if !IsNil(o.MerchantAccountId) {
		toSerialize["merchantAccountId"] = o.MerchantAccountId
	}
	toSerialize["currency"] = o.Currency
	toSerialize["lineItems"] = o.LineItems
	toSerialize["taxMode"] = o.TaxMode
	if !IsNil(o.Taxable) {
		toSerialize["taxable"] = o.Taxable
	}
	if !IsNil(o.TaxBehavior) {
		toSerialize["taxBehavior"] = o.TaxBehavior
	}
	if !IsNil(o.TaxClassificationKey) {
		toSerialize["taxClassificationKey"] = o.TaxClassificationKey
	}
	toSerialize["collectionIntent"] = o.CollectionIntent
	toSerialize["feePolicy"] = o.FeePolicy
	toSerialize["cadence"] = o.Cadence
	toSerialize["endPolicy"] = o.EndPolicy
	toSerialize["startAt"] = o.StartAt
	toSerialize["metadata"] = o.Metadata

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateRecurringPayableRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceType",
		"sourceId",
		"documentId",
		"paymentFieldId",
		"customerExternalId",
		"billingAccountId",
		"currency",
		"lineItems",
		"taxMode",
		"collectionIntent",
		"feePolicy",
		"cadence",
		"endPolicy",
		"startAt",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRecurringPayableRequest := _CreateRecurringPayableRequest{}

	err = json.Unmarshal(data, &varCreateRecurringPayableRequest)

	if err != nil {
		return err
	}

	*o = CreateRecurringPayableRequest(varCreateRecurringPayableRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sourceType")
		delete(additionalProperties, "sourceId")
		delete(additionalProperties, "documentId")
		delete(additionalProperties, "paymentFieldId")
		delete(additionalProperties, "customerExternalId")
		delete(additionalProperties, "billingAccountId")
		delete(additionalProperties, "merchantAccountId")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "lineItems")
		delete(additionalProperties, "taxMode")
		delete(additionalProperties, "taxable")
		delete(additionalProperties, "taxBehavior")
		delete(additionalProperties, "taxClassificationKey")
		delete(additionalProperties, "collectionIntent")
		delete(additionalProperties, "feePolicy")
		delete(additionalProperties, "cadence")
		delete(additionalProperties, "endPolicy")
		delete(additionalProperties, "startAt")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateRecurringPayableRequest struct {
	value *CreateRecurringPayableRequest
	isSet bool
}

func (v NullableCreateRecurringPayableRequest) Get() *CreateRecurringPayableRequest {
	return v.value
}

func (v *NullableCreateRecurringPayableRequest) Set(val *CreateRecurringPayableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRecurringPayableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRecurringPayableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRecurringPayableRequest(val *CreateRecurringPayableRequest) *NullableCreateRecurringPayableRequest {
	return &NullableCreateRecurringPayableRequest{value: val, isSet: true}
}

func (v NullableCreateRecurringPayableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRecurringPayableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
