/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApplyCouponRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyCouponRequest{}

// ApplyCouponRequest struct for ApplyCouponRequest
type ApplyCouponRequest struct {
	AppliedCouponId *string `json:"appliedCouponId,omitempty"`
	CustomerExternalId string `json:"customerExternalId"`
	BillingAccountId *string `json:"billingAccountId,omitempty"`
	SubscriptionExternalId *string `json:"subscriptionExternalId,omitempty"`
	AppliedAt *time.Time `json:"appliedAt,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _ApplyCouponRequest ApplyCouponRequest

// NewApplyCouponRequest instantiates a new ApplyCouponRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyCouponRequest(customerExternalId string) *ApplyCouponRequest {
	this := ApplyCouponRequest{}
	this.CustomerExternalId = customerExternalId
	return &this
}

// NewApplyCouponRequestWithDefaults instantiates a new ApplyCouponRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyCouponRequestWithDefaults() *ApplyCouponRequest {
	this := ApplyCouponRequest{}
	return &this
}

// GetAppliedCouponId returns the AppliedCouponId field value if set, zero value otherwise.
func (o *ApplyCouponRequest) GetAppliedCouponId() string {
	if o == nil || IsNil(o.AppliedCouponId) {
		var ret string
		return ret
	}
	return *o.AppliedCouponId
}

// GetAppliedCouponIdOk returns a tuple with the AppliedCouponId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyCouponRequest) GetAppliedCouponIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppliedCouponId) {
		return nil, false
	}
	return o.AppliedCouponId, true
}

// HasAppliedCouponId returns a boolean if a field has been set.
func (o *ApplyCouponRequest) HasAppliedCouponId() bool {
	if o != nil && !IsNil(o.AppliedCouponId) {
		return true
	}

	return false
}

// SetAppliedCouponId gets a reference to the given string and assigns it to the AppliedCouponId field.
func (o *ApplyCouponRequest) SetAppliedCouponId(v string) {
	o.AppliedCouponId = &v
}

// GetCustomerExternalId returns the CustomerExternalId field value
func (o *ApplyCouponRequest) GetCustomerExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerExternalId
}

// GetCustomerExternalIdOk returns a tuple with the CustomerExternalId field value
// and a boolean to check if the value has been set.
func (o *ApplyCouponRequest) GetCustomerExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerExternalId, true
}

// SetCustomerExternalId sets field value
func (o *ApplyCouponRequest) SetCustomerExternalId(v string) {
	o.CustomerExternalId = v
}

// GetBillingAccountId returns the BillingAccountId field value if set, zero value otherwise.
func (o *ApplyCouponRequest) GetBillingAccountId() string {
	if o == nil || IsNil(o.BillingAccountId) {
		var ret string
		return ret
	}
	return *o.BillingAccountId
}

// GetBillingAccountIdOk returns a tuple with the BillingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyCouponRequest) GetBillingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillingAccountId) {
		return nil, false
	}
	return o.BillingAccountId, true
}

// HasBillingAccountId returns a boolean if a field has been set.
func (o *ApplyCouponRequest) HasBillingAccountId() bool {
	if o != nil && !IsNil(o.BillingAccountId) {
		return true
	}

	return false
}

// SetBillingAccountId gets a reference to the given string and assigns it to the BillingAccountId field.
func (o *ApplyCouponRequest) SetBillingAccountId(v string) {
	o.BillingAccountId = &v
}

// GetSubscriptionExternalId returns the SubscriptionExternalId field value if set, zero value otherwise.
func (o *ApplyCouponRequest) GetSubscriptionExternalId() string {
	if o == nil || IsNil(o.SubscriptionExternalId) {
		var ret string
		return ret
	}
	return *o.SubscriptionExternalId
}

// GetSubscriptionExternalIdOk returns a tuple with the SubscriptionExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyCouponRequest) GetSubscriptionExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionExternalId) {
		return nil, false
	}
	return o.SubscriptionExternalId, true
}

// HasSubscriptionExternalId returns a boolean if a field has been set.
func (o *ApplyCouponRequest) HasSubscriptionExternalId() bool {
	if o != nil && !IsNil(o.SubscriptionExternalId) {
		return true
	}

	return false
}

// SetSubscriptionExternalId gets a reference to the given string and assigns it to the SubscriptionExternalId field.
func (o *ApplyCouponRequest) SetSubscriptionExternalId(v string) {
	o.SubscriptionExternalId = &v
}

// GetAppliedAt returns the AppliedAt field value if set, zero value otherwise.
func (o *ApplyCouponRequest) GetAppliedAt() time.Time {
	if o == nil || IsNil(o.AppliedAt) {
		var ret time.Time
		return ret
	}
	return *o.AppliedAt
}

// GetAppliedAtOk returns a tuple with the AppliedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyCouponRequest) GetAppliedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AppliedAt) {
		return nil, false
	}
	return o.AppliedAt, true
}

// HasAppliedAt returns a boolean if a field has been set.
func (o *ApplyCouponRequest) HasAppliedAt() bool {
	if o != nil && !IsNil(o.AppliedAt) {
		return true
	}

	return false
}

// SetAppliedAt gets a reference to the given time.Time and assigns it to the AppliedAt field.
func (o *ApplyCouponRequest) SetAppliedAt(v time.Time) {
	o.AppliedAt = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ApplyCouponRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyCouponRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ApplyCouponRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *ApplyCouponRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o ApplyCouponRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyCouponRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppliedCouponId) {
		toSerialize["appliedCouponId"] = o.AppliedCouponId
	}
	toSerialize["customerExternalId"] = o.CustomerExternalId
	if !IsNil(o.BillingAccountId) {
		toSerialize["billingAccountId"] = o.BillingAccountId
	}
	if !IsNil(o.SubscriptionExternalId) {
		toSerialize["subscriptionExternalId"] = o.SubscriptionExternalId
	}
	if !IsNil(o.AppliedAt) {
		toSerialize["appliedAt"] = o.AppliedAt
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *ApplyCouponRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerExternalId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyCouponRequest := _ApplyCouponRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyCouponRequest)

	if err != nil {
		return err
	}

	*o = ApplyCouponRequest(varApplyCouponRequest)

	return err
}

type NullableApplyCouponRequest struct {
	value *ApplyCouponRequest
	isSet bool
}

func (v NullableApplyCouponRequest) Get() *ApplyCouponRequest {
	return v.value
}

func (v *NullableApplyCouponRequest) Set(val *ApplyCouponRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyCouponRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyCouponRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyCouponRequest(val *ApplyCouponRequest) *NullableApplyCouponRequest {
	return &NullableApplyCouponRequest{value: val, isSet: true}
}

func (v NullableApplyCouponRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyCouponRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
