/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaxAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxAddress{}

// TaxAddress struct for TaxAddress
type TaxAddress struct {
	Line1 string `json:"line1"`
	Line2 *string `json:"line2,omitempty"`
	City string `json:"city"`
	Region string `json:"region"`
	PostalCode string `json:"postalCode"`
	Country string `json:"country"`
}

type _TaxAddress TaxAddress

// NewTaxAddress instantiates a new TaxAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxAddress(line1 string, city string, region string, postalCode string, country string) *TaxAddress {
	this := TaxAddress{}
	this.Line1 = line1
	this.City = city
	this.Region = region
	this.PostalCode = postalCode
	this.Country = country
	return &this
}

// NewTaxAddressWithDefaults instantiates a new TaxAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxAddressWithDefaults() *TaxAddress {
	this := TaxAddress{}
	return &this
}

// GetLine1 returns the Line1 field value
func (o *TaxAddress) GetLine1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Line1
}

// GetLine1Ok returns a tuple with the Line1 field value
// and a boolean to check if the value has been set.
func (o *TaxAddress) GetLine1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line1, true
}

// SetLine1 sets field value
func (o *TaxAddress) SetLine1(v string) {
	o.Line1 = v
}

// GetLine2 returns the Line2 field value if set, zero value otherwise.
func (o *TaxAddress) GetLine2() string {
	if o == nil || IsNil(o.Line2) {
		var ret string
		return ret
	}
	return *o.Line2
}

// GetLine2Ok returns a tuple with the Line2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxAddress) GetLine2Ok() (*string, bool) {
	if o == nil || IsNil(o.Line2) {
		return nil, false
	}
	return o.Line2, true
}

// HasLine2 returns a boolean if a field has been set.
func (o *TaxAddress) HasLine2() bool {
	if o != nil && !IsNil(o.Line2) {
		return true
	}

	return false
}

// SetLine2 gets a reference to the given string and assigns it to the Line2 field.
func (o *TaxAddress) SetLine2(v string) {
	o.Line2 = &v
}

// GetCity returns the City field value
func (o *TaxAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *TaxAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *TaxAddress) SetCity(v string) {
	o.City = v
}

// GetRegion returns the Region field value
func (o *TaxAddress) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *TaxAddress) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *TaxAddress) SetRegion(v string) {
	o.Region = v
}

// GetPostalCode returns the PostalCode field value
func (o *TaxAddress) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *TaxAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *TaxAddress) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCountry returns the Country field value
func (o *TaxAddress) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *TaxAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *TaxAddress) SetCountry(v string) {
	o.Country = v
}

func (o TaxAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["line1"] = o.Line1
	if !IsNil(o.Line2) {
		toSerialize["line2"] = o.Line2
	}
	toSerialize["city"] = o.City
	toSerialize["region"] = o.Region
	toSerialize["postalCode"] = o.PostalCode
	toSerialize["country"] = o.Country
	return toSerialize, nil
}

func (o *TaxAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"line1",
		"city",
		"region",
		"postalCode",
		"country",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaxAddress := _TaxAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaxAddress)

	if err != nil {
		return err
	}

	*o = TaxAddress(varTaxAddress)

	return err
}

type NullableTaxAddress struct {
	value *TaxAddress
	isSet bool
}

func (v NullableTaxAddress) Get() *TaxAddress {
	return v.value
}

func (v *NullableTaxAddress) Set(val *TaxAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxAddress(val *TaxAddress) *NullableTaxAddress {
	return &NullableTaxAddress{value: val, isSet: true}
}

func (v NullableTaxAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
