/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaxTransactionQuoteRequestLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxTransactionQuoteRequestLinesInner{}

// TaxTransactionQuoteRequestLinesInner struct for TaxTransactionQuoteRequestLinesInner
type TaxTransactionQuoteRequestLinesInner struct {
	SourceLineId string `json:"sourceLineId"`
	Amount int32 `json:"amount"`
	Quantity int32 `json:"quantity"`
	Description *string `json:"description,omitempty"`
	ClassificationKey *string `json:"classificationKey,omitempty"`
	ProductExternalId *string `json:"productExternalId,omitempty"`
	TaxBehavior *TaxBehavior `json:"taxBehavior,omitempty"`
}

type _TaxTransactionQuoteRequestLinesInner TaxTransactionQuoteRequestLinesInner

// NewTaxTransactionQuoteRequestLinesInner instantiates a new TaxTransactionQuoteRequestLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxTransactionQuoteRequestLinesInner(sourceLineId string, amount int32, quantity int32) *TaxTransactionQuoteRequestLinesInner {
	this := TaxTransactionQuoteRequestLinesInner{}
	this.SourceLineId = sourceLineId
	this.Amount = amount
	this.Quantity = quantity
	return &this
}

// NewTaxTransactionQuoteRequestLinesInnerWithDefaults instantiates a new TaxTransactionQuoteRequestLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxTransactionQuoteRequestLinesInnerWithDefaults() *TaxTransactionQuoteRequestLinesInner {
	this := TaxTransactionQuoteRequestLinesInner{}
	return &this
}

// GetSourceLineId returns the SourceLineId field value
func (o *TaxTransactionQuoteRequestLinesInner) GetSourceLineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceLineId
}

// GetSourceLineIdOk returns a tuple with the SourceLineId field value
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetSourceLineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceLineId, true
}

// SetSourceLineId sets field value
func (o *TaxTransactionQuoteRequestLinesInner) SetSourceLineId(v string) {
	o.SourceLineId = v
}

// GetAmount returns the Amount field value
func (o *TaxTransactionQuoteRequestLinesInner) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TaxTransactionQuoteRequestLinesInner) SetAmount(v int32) {
	o.Amount = v
}

// GetQuantity returns the Quantity field value
func (o *TaxTransactionQuoteRequestLinesInner) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *TaxTransactionQuoteRequestLinesInner) SetQuantity(v int32) {
	o.Quantity = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TaxTransactionQuoteRequestLinesInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TaxTransactionQuoteRequestLinesInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TaxTransactionQuoteRequestLinesInner) SetDescription(v string) {
	o.Description = &v
}

// GetClassificationKey returns the ClassificationKey field value if set, zero value otherwise.
func (o *TaxTransactionQuoteRequestLinesInner) GetClassificationKey() string {
	if o == nil || IsNil(o.ClassificationKey) {
		var ret string
		return ret
	}
	return *o.ClassificationKey
}

// GetClassificationKeyOk returns a tuple with the ClassificationKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetClassificationKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ClassificationKey) {
		return nil, false
	}
	return o.ClassificationKey, true
}

// HasClassificationKey returns a boolean if a field has been set.
func (o *TaxTransactionQuoteRequestLinesInner) HasClassificationKey() bool {
	if o != nil && !IsNil(o.ClassificationKey) {
		return true
	}

	return false
}

// SetClassificationKey gets a reference to the given string and assigns it to the ClassificationKey field.
func (o *TaxTransactionQuoteRequestLinesInner) SetClassificationKey(v string) {
	o.ClassificationKey = &v
}

// GetProductExternalId returns the ProductExternalId field value if set, zero value otherwise.
func (o *TaxTransactionQuoteRequestLinesInner) GetProductExternalId() string {
	if o == nil || IsNil(o.ProductExternalId) {
		var ret string
		return ret
	}
	return *o.ProductExternalId
}

// GetProductExternalIdOk returns a tuple with the ProductExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetProductExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductExternalId) {
		return nil, false
	}
	return o.ProductExternalId, true
}

// HasProductExternalId returns a boolean if a field has been set.
func (o *TaxTransactionQuoteRequestLinesInner) HasProductExternalId() bool {
	if o != nil && !IsNil(o.ProductExternalId) {
		return true
	}

	return false
}

// SetProductExternalId gets a reference to the given string and assigns it to the ProductExternalId field.
func (o *TaxTransactionQuoteRequestLinesInner) SetProductExternalId(v string) {
	o.ProductExternalId = &v
}

// GetTaxBehavior returns the TaxBehavior field value if set, zero value otherwise.
func (o *TaxTransactionQuoteRequestLinesInner) GetTaxBehavior() TaxBehavior {
	if o == nil || IsNil(o.TaxBehavior) {
		var ret TaxBehavior
		return ret
	}
	return *o.TaxBehavior
}

// GetTaxBehaviorOk returns a tuple with the TaxBehavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxTransactionQuoteRequestLinesInner) GetTaxBehaviorOk() (*TaxBehavior, bool) {
	if o == nil || IsNil(o.TaxBehavior) {
		return nil, false
	}
	return o.TaxBehavior, true
}

// HasTaxBehavior returns a boolean if a field has been set.
func (o *TaxTransactionQuoteRequestLinesInner) HasTaxBehavior() bool {
	if o != nil && !IsNil(o.TaxBehavior) {
		return true
	}

	return false
}

// SetTaxBehavior gets a reference to the given TaxBehavior and assigns it to the TaxBehavior field.
func (o *TaxTransactionQuoteRequestLinesInner) SetTaxBehavior(v TaxBehavior) {
	o.TaxBehavior = &v
}

func (o TaxTransactionQuoteRequestLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxTransactionQuoteRequestLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceLineId"] = o.SourceLineId
	toSerialize["amount"] = o.Amount
	toSerialize["quantity"] = o.Quantity
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ClassificationKey) {
		toSerialize["classificationKey"] = o.ClassificationKey
	}
	if !IsNil(o.ProductExternalId) {
		toSerialize["productExternalId"] = o.ProductExternalId
	}
	if !IsNil(o.TaxBehavior) {
		toSerialize["taxBehavior"] = o.TaxBehavior
	}
	return toSerialize, nil
}

func (o *TaxTransactionQuoteRequestLinesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceLineId",
		"amount",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaxTransactionQuoteRequestLinesInner := _TaxTransactionQuoteRequestLinesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaxTransactionQuoteRequestLinesInner)

	if err != nil {
		return err
	}

	*o = TaxTransactionQuoteRequestLinesInner(varTaxTransactionQuoteRequestLinesInner)

	return err
}

type NullableTaxTransactionQuoteRequestLinesInner struct {
	value *TaxTransactionQuoteRequestLinesInner
	isSet bool
}

func (v NullableTaxTransactionQuoteRequestLinesInner) Get() *TaxTransactionQuoteRequestLinesInner {
	return v.value
}

func (v *NullableTaxTransactionQuoteRequestLinesInner) Set(val *TaxTransactionQuoteRequestLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxTransactionQuoteRequestLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxTransactionQuoteRequestLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxTransactionQuoteRequestLinesInner(val *TaxTransactionQuoteRequestLinesInner) *NullableTaxTransactionQuoteRequestLinesInner {
	return &NullableTaxTransactionQuoteRequestLinesInner{value: val, isSet: true}
}

func (v NullableTaxTransactionQuoteRequestLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxTransactionQuoteRequestLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
