/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PriceCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceCreateRequest{}

// PriceCreateRequest struct for PriceCreateRequest
type PriceCreateRequest struct {
	PriceId string `json:"priceId"`
	ProductId string `json:"productId"`
	Name string `json:"name"`
	PriceType string `json:"priceType"`
	Currency string `json:"currency"`
	BillingInterval *string `json:"billingInterval,omitempty"`
	BillingIntervalCount *int32 `json:"billingIntervalCount,omitempty"`
	UnitAmount *int32 `json:"unitAmount,omitempty"`
	MeterId *string `json:"meterId,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _PriceCreateRequest PriceCreateRequest

// NewPriceCreateRequest instantiates a new PriceCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceCreateRequest(priceId string, productId string, name string, priceType string, currency string) *PriceCreateRequest {
	this := PriceCreateRequest{}
	this.PriceId = priceId
	this.ProductId = productId
	this.Name = name
	this.PriceType = priceType
	this.Currency = currency
	return &this
}

// NewPriceCreateRequestWithDefaults instantiates a new PriceCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceCreateRequestWithDefaults() *PriceCreateRequest {
	this := PriceCreateRequest{}
	return &this
}

// GetPriceId returns the PriceId field value
func (o *PriceCreateRequest) GetPriceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceId
}

// GetPriceIdOk returns a tuple with the PriceId field value
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetPriceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceId, true
}

// SetPriceId sets field value
func (o *PriceCreateRequest) SetPriceId(v string) {
	o.PriceId = v
}

// GetProductId returns the ProductId field value
func (o *PriceCreateRequest) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *PriceCreateRequest) SetProductId(v string) {
	o.ProductId = v
}

// GetName returns the Name field value
func (o *PriceCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PriceCreateRequest) SetName(v string) {
	o.Name = v
}

// GetPriceType returns the PriceType field value
func (o *PriceCreateRequest) GetPriceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceType
}

// GetPriceTypeOk returns a tuple with the PriceType field value
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetPriceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceType, true
}

// SetPriceType sets field value
func (o *PriceCreateRequest) SetPriceType(v string) {
	o.PriceType = v
}

// GetCurrency returns the Currency field value
func (o *PriceCreateRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PriceCreateRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetBillingInterval returns the BillingInterval field value if set, zero value otherwise.
func (o *PriceCreateRequest) GetBillingInterval() string {
	if o == nil || IsNil(o.BillingInterval) {
		var ret string
		return ret
	}
	return *o.BillingInterval
}

// GetBillingIntervalOk returns a tuple with the BillingInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetBillingIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.BillingInterval) {
		return nil, false
	}
	return o.BillingInterval, true
}

// HasBillingInterval returns a boolean if a field has been set.
func (o *PriceCreateRequest) HasBillingInterval() bool {
	if o != nil && !IsNil(o.BillingInterval) {
		return true
	}

	return false
}

// SetBillingInterval gets a reference to the given string and assigns it to the BillingInterval field.
func (o *PriceCreateRequest) SetBillingInterval(v string) {
	o.BillingInterval = &v
}

// GetBillingIntervalCount returns the BillingIntervalCount field value if set, zero value otherwise.
func (o *PriceCreateRequest) GetBillingIntervalCount() int32 {
	if o == nil || IsNil(o.BillingIntervalCount) {
		var ret int32
		return ret
	}
	return *o.BillingIntervalCount
}

// GetBillingIntervalCountOk returns a tuple with the BillingIntervalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetBillingIntervalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BillingIntervalCount) {
		return nil, false
	}
	return o.BillingIntervalCount, true
}

// HasBillingIntervalCount returns a boolean if a field has been set.
func (o *PriceCreateRequest) HasBillingIntervalCount() bool {
	if o != nil && !IsNil(o.BillingIntervalCount) {
		return true
	}

	return false
}

// SetBillingIntervalCount gets a reference to the given int32 and assigns it to the BillingIntervalCount field.
func (o *PriceCreateRequest) SetBillingIntervalCount(v int32) {
	o.BillingIntervalCount = &v
}

// GetUnitAmount returns the UnitAmount field value if set, zero value otherwise.
func (o *PriceCreateRequest) GetUnitAmount() int32 {
	if o == nil || IsNil(o.UnitAmount) {
		var ret int32
		return ret
	}
	return *o.UnitAmount
}

// GetUnitAmountOk returns a tuple with the UnitAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetUnitAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitAmount) {
		return nil, false
	}
	return o.UnitAmount, true
}

// HasUnitAmount returns a boolean if a field has been set.
func (o *PriceCreateRequest) HasUnitAmount() bool {
	if o != nil && !IsNil(o.UnitAmount) {
		return true
	}

	return false
}

// SetUnitAmount gets a reference to the given int32 and assigns it to the UnitAmount field.
func (o *PriceCreateRequest) SetUnitAmount(v int32) {
	o.UnitAmount = &v
}

// GetMeterId returns the MeterId field value if set, zero value otherwise.
func (o *PriceCreateRequest) GetMeterId() string {
	if o == nil || IsNil(o.MeterId) {
		var ret string
		return ret
	}
	return *o.MeterId
}

// GetMeterIdOk returns a tuple with the MeterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetMeterIdOk() (*string, bool) {
	if o == nil || IsNil(o.MeterId) {
		return nil, false
	}
	return o.MeterId, true
}

// HasMeterId returns a boolean if a field has been set.
func (o *PriceCreateRequest) HasMeterId() bool {
	if o != nil && !IsNil(o.MeterId) {
		return true
	}

	return false
}

// SetMeterId gets a reference to the given string and assigns it to the MeterId field.
func (o *PriceCreateRequest) SetMeterId(v string) {
	o.MeterId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PriceCreateRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceCreateRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PriceCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *PriceCreateRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o PriceCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["priceId"] = o.PriceId
	toSerialize["productId"] = o.ProductId
	toSerialize["name"] = o.Name
	toSerialize["priceType"] = o.PriceType
	toSerialize["currency"] = o.Currency
	if !IsNil(o.BillingInterval) {
		toSerialize["billingInterval"] = o.BillingInterval
	}
	if !IsNil(o.BillingIntervalCount) {
		toSerialize["billingIntervalCount"] = o.BillingIntervalCount
	}
	if !IsNil(o.UnitAmount) {
		toSerialize["unitAmount"] = o.UnitAmount
	}
	if !IsNil(o.MeterId) {
		toSerialize["meterId"] = o.MeterId
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *PriceCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"priceId",
		"productId",
		"name",
		"priceType",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPriceCreateRequest := _PriceCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPriceCreateRequest)

	if err != nil {
		return err
	}

	*o = PriceCreateRequest(varPriceCreateRequest)

	return err
}

type NullablePriceCreateRequest struct {
	value *PriceCreateRequest
	isSet bool
}

func (v NullablePriceCreateRequest) Get() *PriceCreateRequest {
	return v.value
}

func (v *NullablePriceCreateRequest) Set(val *PriceCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceCreateRequest(val *PriceCreateRequest) *NullablePriceCreateRequest {
	return &NullablePriceCreateRequest{value: val, isSet: true}
}

func (v NullablePriceCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
