/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingOrderFormVoidRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingOrderFormVoidRequest{}

// BillingOrderFormVoidRequest struct for BillingOrderFormVoidRequest
type BillingOrderFormVoidRequest struct {
	Reason string `json:"reason"`
}

type _BillingOrderFormVoidRequest BillingOrderFormVoidRequest

// NewBillingOrderFormVoidRequest instantiates a new BillingOrderFormVoidRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingOrderFormVoidRequest(reason string) *BillingOrderFormVoidRequest {
	this := BillingOrderFormVoidRequest{}
	this.Reason = reason
	return &this
}

// NewBillingOrderFormVoidRequestWithDefaults instantiates a new BillingOrderFormVoidRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingOrderFormVoidRequestWithDefaults() *BillingOrderFormVoidRequest {
	this := BillingOrderFormVoidRequest{}
	return &this
}

// GetReason returns the Reason field value
func (o *BillingOrderFormVoidRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *BillingOrderFormVoidRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *BillingOrderFormVoidRequest) SetReason(v string) {
	o.Reason = v
}

func (o BillingOrderFormVoidRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingOrderFormVoidRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *BillingOrderFormVoidRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingOrderFormVoidRequest := _BillingOrderFormVoidRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingOrderFormVoidRequest)

	if err != nil {
		return err
	}

	*o = BillingOrderFormVoidRequest(varBillingOrderFormVoidRequest)

	return err
}

type NullableBillingOrderFormVoidRequest struct {
	value *BillingOrderFormVoidRequest
	isSet bool
}

func (v NullableBillingOrderFormVoidRequest) Get() *BillingOrderFormVoidRequest {
	return v.value
}

func (v *NullableBillingOrderFormVoidRequest) Set(val *BillingOrderFormVoidRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingOrderFormVoidRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingOrderFormVoidRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingOrderFormVoidRequest(val *BillingOrderFormVoidRequest) *NullableBillingOrderFormVoidRequest {
	return &NullableBillingOrderFormVoidRequest{value: val, isSet: true}
}

func (v NullableBillingOrderFormVoidRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingOrderFormVoidRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
