/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"time"
)

// checks if the BillingQuoteVersionApproveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingQuoteVersionApproveRequest{}

// BillingQuoteVersionApproveRequest struct for BillingQuoteVersionApproveRequest
type BillingQuoteVersionApproveRequest struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// NewBillingQuoteVersionApproveRequest instantiates a new BillingQuoteVersionApproveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingQuoteVersionApproveRequest() *BillingQuoteVersionApproveRequest {
	this := BillingQuoteVersionApproveRequest{}
	return &this
}

// NewBillingQuoteVersionApproveRequestWithDefaults instantiates a new BillingQuoteVersionApproveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingQuoteVersionApproveRequestWithDefaults() *BillingQuoteVersionApproveRequest {
	this := BillingQuoteVersionApproveRequest{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *BillingQuoteVersionApproveRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingQuoteVersionApproveRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *BillingQuoteVersionApproveRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *BillingQuoteVersionApproveRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o BillingQuoteVersionApproveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingQuoteVersionApproveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableBillingQuoteVersionApproveRequest struct {
	value *BillingQuoteVersionApproveRequest
	isSet bool
}

func (v NullableBillingQuoteVersionApproveRequest) Get() *BillingQuoteVersionApproveRequest {
	return v.value
}

func (v *NullableBillingQuoteVersionApproveRequest) Set(val *BillingQuoteVersionApproveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingQuoteVersionApproveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingQuoteVersionApproveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingQuoteVersionApproveRequest(val *BillingQuoteVersionApproveRequest) *NullableBillingQuoteVersionApproveRequest {
	return &NullableBillingQuoteVersionApproveRequest{value: val, isSet: true}
}

func (v NullableBillingQuoteVersionApproveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingQuoteVersionApproveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
