/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ExpireCustomerBalanceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpireCustomerBalanceRequest{}

// ExpireCustomerBalanceRequest struct for ExpireCustomerBalanceRequest
type ExpireCustomerBalanceRequest struct {
	EntryId *string `json:"entryId,omitempty"`
	SourceEntryId string `json:"sourceEntryId"`
	Amount *int32 `json:"amount,omitempty"`
	Description *string `json:"description,omitempty"`
	EffectiveAt *time.Time `json:"effectiveAt,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _ExpireCustomerBalanceRequest ExpireCustomerBalanceRequest

// NewExpireCustomerBalanceRequest instantiates a new ExpireCustomerBalanceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpireCustomerBalanceRequest(sourceEntryId string) *ExpireCustomerBalanceRequest {
	this := ExpireCustomerBalanceRequest{}
	this.SourceEntryId = sourceEntryId
	return &this
}

// NewExpireCustomerBalanceRequestWithDefaults instantiates a new ExpireCustomerBalanceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpireCustomerBalanceRequestWithDefaults() *ExpireCustomerBalanceRequest {
	this := ExpireCustomerBalanceRequest{}
	return &this
}

// GetEntryId returns the EntryId field value if set, zero value otherwise.
func (o *ExpireCustomerBalanceRequest) GetEntryId() string {
	if o == nil || IsNil(o.EntryId) {
		var ret string
		return ret
	}
	return *o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpireCustomerBalanceRequest) GetEntryIdOk() (*string, bool) {
	if o == nil || IsNil(o.EntryId) {
		return nil, false
	}
	return o.EntryId, true
}

// HasEntryId returns a boolean if a field has been set.
func (o *ExpireCustomerBalanceRequest) HasEntryId() bool {
	if o != nil && !IsNil(o.EntryId) {
		return true
	}

	return false
}

// SetEntryId gets a reference to the given string and assigns it to the EntryId field.
func (o *ExpireCustomerBalanceRequest) SetEntryId(v string) {
	o.EntryId = &v
}

// GetSourceEntryId returns the SourceEntryId field value
func (o *ExpireCustomerBalanceRequest) GetSourceEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceEntryId
}

// GetSourceEntryIdOk returns a tuple with the SourceEntryId field value
// and a boolean to check if the value has been set.
func (o *ExpireCustomerBalanceRequest) GetSourceEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceEntryId, true
}

// SetSourceEntryId sets field value
func (o *ExpireCustomerBalanceRequest) SetSourceEntryId(v string) {
	o.SourceEntryId = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ExpireCustomerBalanceRequest) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpireCustomerBalanceRequest) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ExpireCustomerBalanceRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ExpireCustomerBalanceRequest) SetAmount(v int32) {
	o.Amount = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ExpireCustomerBalanceRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpireCustomerBalanceRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpireCustomerBalanceRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ExpireCustomerBalanceRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEffectiveAt returns the EffectiveAt field value if set, zero value otherwise.
func (o *ExpireCustomerBalanceRequest) GetEffectiveAt() time.Time {
	if o == nil || IsNil(o.EffectiveAt) {
		var ret time.Time
		return ret
	}
	return *o.EffectiveAt
}

// GetEffectiveAtOk returns a tuple with the EffectiveAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpireCustomerBalanceRequest) GetEffectiveAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EffectiveAt) {
		return nil, false
	}
	return o.EffectiveAt, true
}

// HasEffectiveAt returns a boolean if a field has been set.
func (o *ExpireCustomerBalanceRequest) HasEffectiveAt() bool {
	if o != nil && !IsNil(o.EffectiveAt) {
		return true
	}

	return false
}

// SetEffectiveAt gets a reference to the given time.Time and assigns it to the EffectiveAt field.
func (o *ExpireCustomerBalanceRequest) SetEffectiveAt(v time.Time) {
	o.EffectiveAt = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ExpireCustomerBalanceRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpireCustomerBalanceRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ExpireCustomerBalanceRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *ExpireCustomerBalanceRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o ExpireCustomerBalanceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpireCustomerBalanceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EntryId) {
		toSerialize["entryId"] = o.EntryId
	}
	toSerialize["sourceEntryId"] = o.SourceEntryId
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EffectiveAt) {
		toSerialize["effectiveAt"] = o.EffectiveAt
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *ExpireCustomerBalanceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceEntryId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpireCustomerBalanceRequest := _ExpireCustomerBalanceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpireCustomerBalanceRequest)

	if err != nil {
		return err
	}

	*o = ExpireCustomerBalanceRequest(varExpireCustomerBalanceRequest)

	return err
}

type NullableExpireCustomerBalanceRequest struct {
	value *ExpireCustomerBalanceRequest
	isSet bool
}

func (v NullableExpireCustomerBalanceRequest) Get() *ExpireCustomerBalanceRequest {
	return v.value
}

func (v *NullableExpireCustomerBalanceRequest) Set(val *ExpireCustomerBalanceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpireCustomerBalanceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpireCustomerBalanceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpireCustomerBalanceRequest(val *ExpireCustomerBalanceRequest) *NullableExpireCustomerBalanceRequest {
	return &NullableExpireCustomerBalanceRequest{value: val, isSet: true}
}

func (v NullableExpireCustomerBalanceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpireCustomerBalanceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
