/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerPaymentMethodAttachRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerPaymentMethodAttachRequest{}

// CustomerPaymentMethodAttachRequest struct for CustomerPaymentMethodAttachRequest
type CustomerPaymentMethodAttachRequest struct {
	BillingAccountId *string `json:"billingAccountId,omitempty"`
	PaymentMethodSetupSessionId string `json:"paymentMethodSetupSessionId"`
	SetupToken string `json:"setupToken"`
	SetAsDefault *bool `json:"setAsDefault,omitempty"`
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
}

type _CustomerPaymentMethodAttachRequest CustomerPaymentMethodAttachRequest

// NewCustomerPaymentMethodAttachRequest instantiates a new CustomerPaymentMethodAttachRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerPaymentMethodAttachRequest(paymentMethodSetupSessionId string, setupToken string) *CustomerPaymentMethodAttachRequest {
	this := CustomerPaymentMethodAttachRequest{}
	this.PaymentMethodSetupSessionId = paymentMethodSetupSessionId
	this.SetupToken = setupToken
	return &this
}

// NewCustomerPaymentMethodAttachRequestWithDefaults instantiates a new CustomerPaymentMethodAttachRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerPaymentMethodAttachRequestWithDefaults() *CustomerPaymentMethodAttachRequest {
	this := CustomerPaymentMethodAttachRequest{}
	return &this
}

// GetBillingAccountId returns the BillingAccountId field value if set, zero value otherwise.
func (o *CustomerPaymentMethodAttachRequest) GetBillingAccountId() string {
	if o == nil || IsNil(o.BillingAccountId) {
		var ret string
		return ret
	}
	return *o.BillingAccountId
}

// GetBillingAccountIdOk returns a tuple with the BillingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodAttachRequest) GetBillingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillingAccountId) {
		return nil, false
	}
	return o.BillingAccountId, true
}

// HasBillingAccountId returns a boolean if a field has been set.
func (o *CustomerPaymentMethodAttachRequest) HasBillingAccountId() bool {
	if o != nil && !IsNil(o.BillingAccountId) {
		return true
	}

	return false
}

// SetBillingAccountId gets a reference to the given string and assigns it to the BillingAccountId field.
func (o *CustomerPaymentMethodAttachRequest) SetBillingAccountId(v string) {
	o.BillingAccountId = &v
}

// GetPaymentMethodSetupSessionId returns the PaymentMethodSetupSessionId field value
func (o *CustomerPaymentMethodAttachRequest) GetPaymentMethodSetupSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethodSetupSessionId
}

// GetPaymentMethodSetupSessionIdOk returns a tuple with the PaymentMethodSetupSessionId field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodAttachRequest) GetPaymentMethodSetupSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethodSetupSessionId, true
}

// SetPaymentMethodSetupSessionId sets field value
func (o *CustomerPaymentMethodAttachRequest) SetPaymentMethodSetupSessionId(v string) {
	o.PaymentMethodSetupSessionId = v
}

// GetSetupToken returns the SetupToken field value
func (o *CustomerPaymentMethodAttachRequest) GetSetupToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SetupToken
}

// GetSetupTokenOk returns a tuple with the SetupToken field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodAttachRequest) GetSetupTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SetupToken, true
}

// SetSetupToken sets field value
func (o *CustomerPaymentMethodAttachRequest) SetSetupToken(v string) {
	o.SetupToken = v
}

// GetSetAsDefault returns the SetAsDefault field value if set, zero value otherwise.
func (o *CustomerPaymentMethodAttachRequest) GetSetAsDefault() bool {
	if o == nil || IsNil(o.SetAsDefault) {
		var ret bool
		return ret
	}
	return *o.SetAsDefault
}

// GetSetAsDefaultOk returns a tuple with the SetAsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodAttachRequest) GetSetAsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.SetAsDefault) {
		return nil, false
	}
	return o.SetAsDefault, true
}

// HasSetAsDefault returns a boolean if a field has been set.
func (o *CustomerPaymentMethodAttachRequest) HasSetAsDefault() bool {
	if o != nil && !IsNil(o.SetAsDefault) {
		return true
	}

	return false
}

// SetSetAsDefault gets a reference to the given bool and assigns it to the SetAsDefault field.
func (o *CustomerPaymentMethodAttachRequest) SetSetAsDefault(v bool) {
	o.SetAsDefault = &v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *CustomerPaymentMethodAttachRequest) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodAttachRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *CustomerPaymentMethodAttachRequest) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *CustomerPaymentMethodAttachRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

func (o CustomerPaymentMethodAttachRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerPaymentMethodAttachRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingAccountId) {
		toSerialize["billingAccountId"] = o.BillingAccountId
	}
	toSerialize["paymentMethodSetupSessionId"] = o.PaymentMethodSetupSessionId
	toSerialize["setupToken"] = o.SetupToken
	if !IsNil(o.SetAsDefault) {
		toSerialize["setAsDefault"] = o.SetAsDefault
	}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotencyKey"] = o.IdempotencyKey
	}
	return toSerialize, nil
}

func (o *CustomerPaymentMethodAttachRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paymentMethodSetupSessionId",
		"setupToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerPaymentMethodAttachRequest := _CustomerPaymentMethodAttachRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerPaymentMethodAttachRequest)

	if err != nil {
		return err
	}

	*o = CustomerPaymentMethodAttachRequest(varCustomerPaymentMethodAttachRequest)

	return err
}

type NullableCustomerPaymentMethodAttachRequest struct {
	value *CustomerPaymentMethodAttachRequest
	isSet bool
}

func (v NullableCustomerPaymentMethodAttachRequest) Get() *CustomerPaymentMethodAttachRequest {
	return v.value
}

func (v *NullableCustomerPaymentMethodAttachRequest) Set(val *CustomerPaymentMethodAttachRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerPaymentMethodAttachRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerPaymentMethodAttachRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerPaymentMethodAttachRequest(val *CustomerPaymentMethodAttachRequest) *NullableCustomerPaymentMethodAttachRequest {
	return &NullableCustomerPaymentMethodAttachRequest{value: val, isSet: true}
}

func (v NullableCustomerPaymentMethodAttachRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerPaymentMethodAttachRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
