/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
)

// checks if the WebhookDeliveriesRedriveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveriesRedriveRequest{}

// WebhookDeliveriesRedriveRequest struct for WebhookDeliveriesRedriveRequest
type WebhookDeliveriesRedriveRequest struct {
	EventId *string `json:"eventId,omitempty"`
	EndpointId *string `json:"endpointId,omitempty"`
	FailureKind *string `json:"failureKind,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	ReplayedByRef *string `json:"replayedByRef,omitempty"`
	Dispatch *bool `json:"dispatch,omitempty"`
}

// NewWebhookDeliveriesRedriveRequest instantiates a new WebhookDeliveriesRedriveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveriesRedriveRequest() *WebhookDeliveriesRedriveRequest {
	this := WebhookDeliveriesRedriveRequest{}
	return &this
}

// NewWebhookDeliveriesRedriveRequestWithDefaults instantiates a new WebhookDeliveriesRedriveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveriesRedriveRequestWithDefaults() *WebhookDeliveriesRedriveRequest {
	this := WebhookDeliveriesRedriveRequest{}
	return &this
}

// GetEventId returns the EventId field value if set, zero value otherwise.
func (o *WebhookDeliveriesRedriveRequest) GetEventId() string {
	if o == nil || IsNil(o.EventId) {
		var ret string
		return ret
	}
	return *o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesRedriveRequest) GetEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.EventId) {
		return nil, false
	}
	return o.EventId, true
}

// HasEventId returns a boolean if a field has been set.
func (o *WebhookDeliveriesRedriveRequest) HasEventId() bool {
	if o != nil && !IsNil(o.EventId) {
		return true
	}

	return false
}

// SetEventId gets a reference to the given string and assigns it to the EventId field.
func (o *WebhookDeliveriesRedriveRequest) SetEventId(v string) {
	o.EventId = &v
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *WebhookDeliveriesRedriveRequest) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesRedriveRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *WebhookDeliveriesRedriveRequest) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *WebhookDeliveriesRedriveRequest) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetFailureKind returns the FailureKind field value if set, zero value otherwise.
func (o *WebhookDeliveriesRedriveRequest) GetFailureKind() string {
	if o == nil || IsNil(o.FailureKind) {
		var ret string
		return ret
	}
	return *o.FailureKind
}

// GetFailureKindOk returns a tuple with the FailureKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesRedriveRequest) GetFailureKindOk() (*string, bool) {
	if o == nil || IsNil(o.FailureKind) {
		return nil, false
	}
	return o.FailureKind, true
}

// HasFailureKind returns a boolean if a field has been set.
func (o *WebhookDeliveriesRedriveRequest) HasFailureKind() bool {
	if o != nil && !IsNil(o.FailureKind) {
		return true
	}

	return false
}

// SetFailureKind gets a reference to the given string and assigns it to the FailureKind field.
func (o *WebhookDeliveriesRedriveRequest) SetFailureKind(v string) {
	o.FailureKind = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *WebhookDeliveriesRedriveRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesRedriveRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *WebhookDeliveriesRedriveRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *WebhookDeliveriesRedriveRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetReplayedByRef returns the ReplayedByRef field value if set, zero value otherwise.
func (o *WebhookDeliveriesRedriveRequest) GetReplayedByRef() string {
	if o == nil || IsNil(o.ReplayedByRef) {
		var ret string
		return ret
	}
	return *o.ReplayedByRef
}

// GetReplayedByRefOk returns a tuple with the ReplayedByRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesRedriveRequest) GetReplayedByRefOk() (*string, bool) {
	if o == nil || IsNil(o.ReplayedByRef) {
		return nil, false
	}
	return o.ReplayedByRef, true
}

// HasReplayedByRef returns a boolean if a field has been set.
func (o *WebhookDeliveriesRedriveRequest) HasReplayedByRef() bool {
	if o != nil && !IsNil(o.ReplayedByRef) {
		return true
	}

	return false
}

// SetReplayedByRef gets a reference to the given string and assigns it to the ReplayedByRef field.
func (o *WebhookDeliveriesRedriveRequest) SetReplayedByRef(v string) {
	o.ReplayedByRef = &v
}

// GetDispatch returns the Dispatch field value if set, zero value otherwise.
func (o *WebhookDeliveriesRedriveRequest) GetDispatch() bool {
	if o == nil || IsNil(o.Dispatch) {
		var ret bool
		return ret
	}
	return *o.Dispatch
}

// GetDispatchOk returns a tuple with the Dispatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesRedriveRequest) GetDispatchOk() (*bool, bool) {
	if o == nil || IsNil(o.Dispatch) {
		return nil, false
	}
	return o.Dispatch, true
}

// HasDispatch returns a boolean if a field has been set.
func (o *WebhookDeliveriesRedriveRequest) HasDispatch() bool {
	if o != nil && !IsNil(o.Dispatch) {
		return true
	}

	return false
}

// SetDispatch gets a reference to the given bool and assigns it to the Dispatch field.
func (o *WebhookDeliveriesRedriveRequest) SetDispatch(v bool) {
	o.Dispatch = &v
}

func (o WebhookDeliveriesRedriveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveriesRedriveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventId) {
		toSerialize["eventId"] = o.EventId
	}
	if !IsNil(o.EndpointId) {
		toSerialize["endpointId"] = o.EndpointId
	}
	if !IsNil(o.FailureKind) {
		toSerialize["failureKind"] = o.FailureKind
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.ReplayedByRef) {
		toSerialize["replayedByRef"] = o.ReplayedByRef
	}
	if !IsNil(o.Dispatch) {
		toSerialize["dispatch"] = o.Dispatch
	}
	return toSerialize, nil
}

type NullableWebhookDeliveriesRedriveRequest struct {
	value *WebhookDeliveriesRedriveRequest
	isSet bool
}

func (v NullableWebhookDeliveriesRedriveRequest) Get() *WebhookDeliveriesRedriveRequest {
	return v.value
}

func (v *NullableWebhookDeliveriesRedriveRequest) Set(val *WebhookDeliveriesRedriveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveriesRedriveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveriesRedriveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveriesRedriveRequest(val *WebhookDeliveriesRedriveRequest) *NullableWebhookDeliveriesRedriveRequest {
	return &NullableWebhookDeliveriesRedriveRequest{value: val, isSet: true}
}

func (v NullableWebhookDeliveriesRedriveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveriesRedriveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
