/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortex

import (
	"encoding/json"
)

// checks if the MerchantOnboardingSubmitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantOnboardingSubmitRequest{}

// MerchantOnboardingSubmitRequest struct for MerchantOnboardingSubmitRequest
type MerchantOnboardingSubmitRequest struct {
	Environment *string `json:"environment,omitempty"`
	SubmittedByType *string `json:"submittedByType,omitempty"`
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
	// Captured from request headers when omitted — explicit supply keeps hosted submits honest.
	MerchantAgreementIpAddress *string `json:"merchantAgreementIpAddress,omitempty"`
	MerchantAgreementUserAgent *string `json:"merchantAgreementUserAgent,omitempty"`
}

// NewMerchantOnboardingSubmitRequest instantiates a new MerchantOnboardingSubmitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantOnboardingSubmitRequest() *MerchantOnboardingSubmitRequest {
	this := MerchantOnboardingSubmitRequest{}
	return &this
}

// NewMerchantOnboardingSubmitRequestWithDefaults instantiates a new MerchantOnboardingSubmitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantOnboardingSubmitRequestWithDefaults() *MerchantOnboardingSubmitRequest {
	this := MerchantOnboardingSubmitRequest{}
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *MerchantOnboardingSubmitRequest) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingSubmitRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *MerchantOnboardingSubmitRequest) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *MerchantOnboardingSubmitRequest) SetEnvironment(v string) {
	o.Environment = &v
}

// GetSubmittedByType returns the SubmittedByType field value if set, zero value otherwise.
func (o *MerchantOnboardingSubmitRequest) GetSubmittedByType() string {
	if o == nil || IsNil(o.SubmittedByType) {
		var ret string
		return ret
	}
	return *o.SubmittedByType
}

// GetSubmittedByTypeOk returns a tuple with the SubmittedByType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingSubmitRequest) GetSubmittedByTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SubmittedByType) {
		return nil, false
	}
	return o.SubmittedByType, true
}

// HasSubmittedByType returns a boolean if a field has been set.
func (o *MerchantOnboardingSubmitRequest) HasSubmittedByType() bool {
	if o != nil && !IsNil(o.SubmittedByType) {
		return true
	}

	return false
}

// SetSubmittedByType gets a reference to the given string and assigns it to the SubmittedByType field.
func (o *MerchantOnboardingSubmitRequest) SetSubmittedByType(v string) {
	o.SubmittedByType = &v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *MerchantOnboardingSubmitRequest) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingSubmitRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *MerchantOnboardingSubmitRequest) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *MerchantOnboardingSubmitRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

// GetMerchantAgreementIpAddress returns the MerchantAgreementIpAddress field value if set, zero value otherwise.
func (o *MerchantOnboardingSubmitRequest) GetMerchantAgreementIpAddress() string {
	if o == nil || IsNil(o.MerchantAgreementIpAddress) {
		var ret string
		return ret
	}
	return *o.MerchantAgreementIpAddress
}

// GetMerchantAgreementIpAddressOk returns a tuple with the MerchantAgreementIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingSubmitRequest) GetMerchantAgreementIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantAgreementIpAddress) {
		return nil, false
	}
	return o.MerchantAgreementIpAddress, true
}

// HasMerchantAgreementIpAddress returns a boolean if a field has been set.
func (o *MerchantOnboardingSubmitRequest) HasMerchantAgreementIpAddress() bool {
	if o != nil && !IsNil(o.MerchantAgreementIpAddress) {
		return true
	}

	return false
}

// SetMerchantAgreementIpAddress gets a reference to the given string and assigns it to the MerchantAgreementIpAddress field.
func (o *MerchantOnboardingSubmitRequest) SetMerchantAgreementIpAddress(v string) {
	o.MerchantAgreementIpAddress = &v
}

// GetMerchantAgreementUserAgent returns the MerchantAgreementUserAgent field value if set, zero value otherwise.
func (o *MerchantOnboardingSubmitRequest) GetMerchantAgreementUserAgent() string {
	if o == nil || IsNil(o.MerchantAgreementUserAgent) {
		var ret string
		return ret
	}
	return *o.MerchantAgreementUserAgent
}

// GetMerchantAgreementUserAgentOk returns a tuple with the MerchantAgreementUserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingSubmitRequest) GetMerchantAgreementUserAgentOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantAgreementUserAgent) {
		return nil, false
	}
	return o.MerchantAgreementUserAgent, true
}

// HasMerchantAgreementUserAgent returns a boolean if a field has been set.
func (o *MerchantOnboardingSubmitRequest) HasMerchantAgreementUserAgent() bool {
	if o != nil && !IsNil(o.MerchantAgreementUserAgent) {
		return true
	}

	return false
}

// SetMerchantAgreementUserAgent gets a reference to the given string and assigns it to the MerchantAgreementUserAgent field.
func (o *MerchantOnboardingSubmitRequest) SetMerchantAgreementUserAgent(v string) {
	o.MerchantAgreementUserAgent = &v
}

func (o MerchantOnboardingSubmitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantOnboardingSubmitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.SubmittedByType) {
		toSerialize["submittedByType"] = o.SubmittedByType
	}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotencyKey"] = o.IdempotencyKey
	}
	if !IsNil(o.MerchantAgreementIpAddress) {
		toSerialize["merchantAgreementIpAddress"] = o.MerchantAgreementIpAddress
	}
	if !IsNil(o.MerchantAgreementUserAgent) {
		toSerialize["merchantAgreementUserAgent"] = o.MerchantAgreementUserAgent
	}
	return toSerialize, nil
}

type NullableMerchantOnboardingSubmitRequest struct {
	value *MerchantOnboardingSubmitRequest
	isSet bool
}

func (v NullableMerchantOnboardingSubmitRequest) Get() *MerchantOnboardingSubmitRequest {
	return v.value
}

func (v *NullableMerchantOnboardingSubmitRequest) Set(val *MerchantOnboardingSubmitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantOnboardingSubmitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantOnboardingSubmitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantOnboardingSubmitRequest(val *MerchantOnboardingSubmitRequest) *NullableMerchantOnboardingSubmitRequest {
	return &NullableMerchantOnboardingSubmitRequest{value: val, isSet: true}
}

func (v NullableMerchantOnboardingSubmitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantOnboardingSubmitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
