/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantAddress{}

// MerchantAddress struct for MerchantAddress
type MerchantAddress struct {
	Line1 string `json:"line1"`
	Line2 *string `json:"line2,omitempty"`
	City string `json:"city"`
	Region *string `json:"region,omitempty"`
	PostalCode string `json:"postalCode"`
	Country string `json:"country"`
}

type _MerchantAddress MerchantAddress

// NewMerchantAddress instantiates a new MerchantAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantAddress(line1 string, city string, postalCode string, country string) *MerchantAddress {
	this := MerchantAddress{}
	this.Line1 = line1
	this.City = city
	this.PostalCode = postalCode
	this.Country = country
	return &this
}

// NewMerchantAddressWithDefaults instantiates a new MerchantAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantAddressWithDefaults() *MerchantAddress {
	this := MerchantAddress{}
	return &this
}

// GetLine1 returns the Line1 field value
func (o *MerchantAddress) GetLine1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Line1
}

// GetLine1Ok returns a tuple with the Line1 field value
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetLine1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line1, true
}

// SetLine1 sets field value
func (o *MerchantAddress) SetLine1(v string) {
	o.Line1 = v
}

// GetLine2 returns the Line2 field value if set, zero value otherwise.
func (o *MerchantAddress) GetLine2() string {
	if o == nil || IsNil(o.Line2) {
		var ret string
		return ret
	}
	return *o.Line2
}

// GetLine2Ok returns a tuple with the Line2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetLine2Ok() (*string, bool) {
	if o == nil || IsNil(o.Line2) {
		return nil, false
	}
	return o.Line2, true
}

// HasLine2 returns a boolean if a field has been set.
func (o *MerchantAddress) HasLine2() bool {
	if o != nil && !IsNil(o.Line2) {
		return true
	}

	return false
}

// SetLine2 gets a reference to the given string and assigns it to the Line2 field.
func (o *MerchantAddress) SetLine2(v string) {
	o.Line2 = &v
}

// GetCity returns the City field value
func (o *MerchantAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *MerchantAddress) SetCity(v string) {
	o.City = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *MerchantAddress) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *MerchantAddress) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *MerchantAddress) SetRegion(v string) {
	o.Region = &v
}

// GetPostalCode returns the PostalCode field value
func (o *MerchantAddress) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *MerchantAddress) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCountry returns the Country field value
func (o *MerchantAddress) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *MerchantAddress) SetCountry(v string) {
	o.Country = v
}

func (o MerchantAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["line1"] = o.Line1
	if !IsNil(o.Line2) {
		toSerialize["line2"] = o.Line2
	}
	toSerialize["city"] = o.City
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	toSerialize["postalCode"] = o.PostalCode
	toSerialize["country"] = o.Country
	return toSerialize, nil
}

func (o *MerchantAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"line1",
		"city",
		"postalCode",
		"country",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantAddress := _MerchantAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantAddress)

	if err != nil {
		return err
	}

	*o = MerchantAddress(varMerchantAddress)

	return err
}

type NullableMerchantAddress struct {
	value *MerchantAddress
	isSet bool
}

func (v NullableMerchantAddress) Get() *MerchantAddress {
	return v.value
}

func (v *NullableMerchantAddress) Set(val *MerchantAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantAddress(val *MerchantAddress) *NullableMerchantAddress {
	return &NullableMerchantAddress{value: val, isSet: true}
}

func (v NullableMerchantAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
