/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"time"
)

// checks if the PaymentRequestLinkCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRequestLinkCreateRequest{}

// PaymentRequestLinkCreateRequest struct for PaymentRequestLinkCreateRequest
type PaymentRequestLinkCreateRequest struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	CreatedByRef *string `json:"createdByRef,omitempty"`
}

// NewPaymentRequestLinkCreateRequest instantiates a new PaymentRequestLinkCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequestLinkCreateRequest() *PaymentRequestLinkCreateRequest {
	this := PaymentRequestLinkCreateRequest{}
	return &this
}

// NewPaymentRequestLinkCreateRequestWithDefaults instantiates a new PaymentRequestLinkCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestLinkCreateRequestWithDefaults() *PaymentRequestLinkCreateRequest {
	this := PaymentRequestLinkCreateRequest{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *PaymentRequestLinkCreateRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRequestLinkCreateRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *PaymentRequestLinkCreateRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *PaymentRequestLinkCreateRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetCreatedByRef returns the CreatedByRef field value if set, zero value otherwise.
func (o *PaymentRequestLinkCreateRequest) GetCreatedByRef() string {
	if o == nil || IsNil(o.CreatedByRef) {
		var ret string
		return ret
	}
	return *o.CreatedByRef
}

// GetCreatedByRefOk returns a tuple with the CreatedByRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRequestLinkCreateRequest) GetCreatedByRefOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByRef) {
		return nil, false
	}
	return o.CreatedByRef, true
}

// HasCreatedByRef returns a boolean if a field has been set.
func (o *PaymentRequestLinkCreateRequest) HasCreatedByRef() bool {
	if o != nil && !IsNil(o.CreatedByRef) {
		return true
	}

	return false
}

// SetCreatedByRef gets a reference to the given string and assigns it to the CreatedByRef field.
func (o *PaymentRequestLinkCreateRequest) SetCreatedByRef(v string) {
	o.CreatedByRef = &v
}

func (o PaymentRequestLinkCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRequestLinkCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.CreatedByRef) {
		toSerialize["createdByRef"] = o.CreatedByRef
	}
	return toSerialize, nil
}

type NullablePaymentRequestLinkCreateRequest struct {
	value *PaymentRequestLinkCreateRequest
	isSet bool
}

func (v NullablePaymentRequestLinkCreateRequest) Get() *PaymentRequestLinkCreateRequest {
	return v.value
}

func (v *NullablePaymentRequestLinkCreateRequest) Set(val *PaymentRequestLinkCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequestLinkCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequestLinkCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequestLinkCreateRequest(val *PaymentRequestLinkCreateRequest) *NullablePaymentRequestLinkCreateRequest {
	return &NullablePaymentRequestLinkCreateRequest{value: val, isSet: true}
}

func (v NullablePaymentRequestLinkCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequestLinkCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
