/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckoutSessionLineItemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutSessionLineItemRequest{}

// CheckoutSessionLineItemRequest struct for CheckoutSessionLineItemRequest
type CheckoutSessionLineItemRequest struct {
	PriceId string `json:"priceId"`
	Quantity *int32 `json:"quantity,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _CheckoutSessionLineItemRequest CheckoutSessionLineItemRequest

// NewCheckoutSessionLineItemRequest instantiates a new CheckoutSessionLineItemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutSessionLineItemRequest(priceId string) *CheckoutSessionLineItemRequest {
	this := CheckoutSessionLineItemRequest{}
	this.PriceId = priceId
	return &this
}

// NewCheckoutSessionLineItemRequestWithDefaults instantiates a new CheckoutSessionLineItemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutSessionLineItemRequestWithDefaults() *CheckoutSessionLineItemRequest {
	this := CheckoutSessionLineItemRequest{}
	return &this
}

// GetPriceId returns the PriceId field value
func (o *CheckoutSessionLineItemRequest) GetPriceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceId
}

// GetPriceIdOk returns a tuple with the PriceId field value
// and a boolean to check if the value has been set.
func (o *CheckoutSessionLineItemRequest) GetPriceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceId, true
}

// SetPriceId sets field value
func (o *CheckoutSessionLineItemRequest) SetPriceId(v string) {
	o.PriceId = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CheckoutSessionLineItemRequest) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutSessionLineItemRequest) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CheckoutSessionLineItemRequest) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *CheckoutSessionLineItemRequest) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CheckoutSessionLineItemRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutSessionLineItemRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CheckoutSessionLineItemRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CheckoutSessionLineItemRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o CheckoutSessionLineItemRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutSessionLineItemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["priceId"] = o.PriceId
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CheckoutSessionLineItemRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"priceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckoutSessionLineItemRequest := _CheckoutSessionLineItemRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckoutSessionLineItemRequest)

	if err != nil {
		return err
	}

	*o = CheckoutSessionLineItemRequest(varCheckoutSessionLineItemRequest)

	return err
}

type NullableCheckoutSessionLineItemRequest struct {
	value *CheckoutSessionLineItemRequest
	isSet bool
}

func (v NullableCheckoutSessionLineItemRequest) Get() *CheckoutSessionLineItemRequest {
	return v.value
}

func (v *NullableCheckoutSessionLineItemRequest) Set(val *CheckoutSessionLineItemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutSessionLineItemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutSessionLineItemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutSessionLineItemRequest(val *CheckoutSessionLineItemRequest) *NullableCheckoutSessionLineItemRequest {
	return &NullableCheckoutSessionLineItemRequest{value: val, isSet: true}
}

func (v NullableCheckoutSessionLineItemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutSessionLineItemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
