/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantOnboardingLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantOnboardingLinkRequest{}

// MerchantOnboardingLinkRequest struct for MerchantOnboardingLinkRequest
type MerchantOnboardingLinkRequest struct {
	Environment string `json:"environment"`
	CreatedByRef string `json:"createdByRef"`
}

type _MerchantOnboardingLinkRequest MerchantOnboardingLinkRequest

// NewMerchantOnboardingLinkRequest instantiates a new MerchantOnboardingLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantOnboardingLinkRequest(environment string, createdByRef string) *MerchantOnboardingLinkRequest {
	this := MerchantOnboardingLinkRequest{}
	this.Environment = environment
	this.CreatedByRef = createdByRef
	return &this
}

// NewMerchantOnboardingLinkRequestWithDefaults instantiates a new MerchantOnboardingLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantOnboardingLinkRequestWithDefaults() *MerchantOnboardingLinkRequest {
	this := MerchantOnboardingLinkRequest{}
	return &this
}

// GetEnvironment returns the Environment field value
func (o *MerchantOnboardingLinkRequest) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingLinkRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *MerchantOnboardingLinkRequest) SetEnvironment(v string) {
	o.Environment = v
}

// GetCreatedByRef returns the CreatedByRef field value
func (o *MerchantOnboardingLinkRequest) GetCreatedByRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedByRef
}

// GetCreatedByRefOk returns a tuple with the CreatedByRef field value
// and a boolean to check if the value has been set.
func (o *MerchantOnboardingLinkRequest) GetCreatedByRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByRef, true
}

// SetCreatedByRef sets field value
func (o *MerchantOnboardingLinkRequest) SetCreatedByRef(v string) {
	o.CreatedByRef = v
}

func (o MerchantOnboardingLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantOnboardingLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment"] = o.Environment
	toSerialize["createdByRef"] = o.CreatedByRef
	return toSerialize, nil
}

func (o *MerchantOnboardingLinkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environment",
		"createdByRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantOnboardingLinkRequest := _MerchantOnboardingLinkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantOnboardingLinkRequest)

	if err != nil {
		return err
	}

	*o = MerchantOnboardingLinkRequest(varMerchantOnboardingLinkRequest)

	return err
}

type NullableMerchantOnboardingLinkRequest struct {
	value *MerchantOnboardingLinkRequest
	isSet bool
}

func (v NullableMerchantOnboardingLinkRequest) Get() *MerchantOnboardingLinkRequest {
	return v.value
}

func (v *NullableMerchantOnboardingLinkRequest) Set(val *MerchantOnboardingLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantOnboardingLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantOnboardingLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantOnboardingLinkRequest(val *MerchantOnboardingLinkRequest) *NullableMerchantOnboardingLinkRequest {
	return &NullableMerchantOnboardingLinkRequest{value: val, isSet: true}
}

func (v NullableMerchantOnboardingLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantOnboardingLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
