/*
Vortex Payments API

Public Vortex Payments API for customers, subscriptions, invoices, payment requests, checkout, receipts, webhooks, tax.

API version: 2026-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vortexpayments

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenApiInvoiceTaxResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenApiInvoiceTaxResponse{}

// OpenApiInvoiceTaxResponse struct for OpenApiInvoiceTaxResponse
type OpenApiInvoiceTaxResponse struct {
	Data OpenApiInvoiceTaxResponseAllOfData `json:"data"`
	RequestId string `json:"requestId"`
}

type _OpenApiInvoiceTaxResponse OpenApiInvoiceTaxResponse

// NewOpenApiInvoiceTaxResponse instantiates a new OpenApiInvoiceTaxResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenApiInvoiceTaxResponse(data OpenApiInvoiceTaxResponseAllOfData, requestId string) *OpenApiInvoiceTaxResponse {
	this := OpenApiInvoiceTaxResponse{}
	this.Data = data
	this.RequestId = requestId
	return &this
}

// NewOpenApiInvoiceTaxResponseWithDefaults instantiates a new OpenApiInvoiceTaxResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenApiInvoiceTaxResponseWithDefaults() *OpenApiInvoiceTaxResponse {
	this := OpenApiInvoiceTaxResponse{}
	return &this
}

// GetData returns the Data field value
func (o *OpenApiInvoiceTaxResponse) GetData() OpenApiInvoiceTaxResponseAllOfData {
	if o == nil {
		var ret OpenApiInvoiceTaxResponseAllOfData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OpenApiInvoiceTaxResponse) GetDataOk() (*OpenApiInvoiceTaxResponseAllOfData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OpenApiInvoiceTaxResponse) SetData(v OpenApiInvoiceTaxResponseAllOfData) {
	o.Data = v
}

// GetRequestId returns the RequestId field value
func (o *OpenApiInvoiceTaxResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *OpenApiInvoiceTaxResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *OpenApiInvoiceTaxResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o OpenApiInvoiceTaxResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenApiInvoiceTaxResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["requestId"] = o.RequestId
	return toSerialize, nil
}

func (o *OpenApiInvoiceTaxResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"requestId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenApiInvoiceTaxResponse := _OpenApiInvoiceTaxResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenApiInvoiceTaxResponse)

	if err != nil {
		return err
	}

	*o = OpenApiInvoiceTaxResponse(varOpenApiInvoiceTaxResponse)

	return err
}

type NullableOpenApiInvoiceTaxResponse struct {
	value *OpenApiInvoiceTaxResponse
	isSet bool
}

func (v NullableOpenApiInvoiceTaxResponse) Get() *OpenApiInvoiceTaxResponse {
	return v.value
}

func (v *NullableOpenApiInvoiceTaxResponse) Set(val *OpenApiInvoiceTaxResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenApiInvoiceTaxResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenApiInvoiceTaxResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenApiInvoiceTaxResponse(val *OpenApiInvoiceTaxResponse) *NullableOpenApiInvoiceTaxResponse {
	return &NullableOpenApiInvoiceTaxResponse{value: val, isSet: true}
}

func (v NullableOpenApiInvoiceTaxResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenApiInvoiceTaxResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
